"""
Production Operations Layer (Commit 27 Part 1.1, 1.2).

Operations = 看清楚系统发生了什么
Control    = 决定系统允许做什么
Recovery   = 决定系统什么时候可以重新做

重要边界（spec sections 16-18）：

1. Operational Health 不是 Trading Health：
   Service = HEALTHY 不代表 Trading = SAFE（Position != Ledger 时
   Trading State = NOT SAFE）。

2. Operations 只负责 Observe，不执行控制：
   正确路径是 Operations -> Health Signal -> Incident -> Control Plane
   -> Kill / Pause / Failover。Observability 代码绝不能偷偷拥有交易
   控制权限。

3. Telemetry 只负责记录，不参与交易决策（Part 1.2 spec section 23）：
   Metrics 描述"系统现在怎么样"，Telemetry 描述"系统刚刚发生了什么"。
   错误：if latency > 500: reject_order()

4. Alert 是"发现异常"，不是"执行交易控制"（Part 1.3 spec section 29）：
   Kill / Pause / Freeze / Failover / Recovery 仍由 Control Plane 执行。
"""

from .alerting import (
    Alert,
    AlertDeduplicator,
    AlertFingerprint,
    AlertManager,
    AlertRule,
    AlertRuleEvaluator,
    AlertRouter,
    AlertSeverity,
    AlertState,
    AlertStormProtector,
    ConditionEvaluator,
    FlappingDetector,
    standard_rules,
)
from .health import ServiceHealthMonitor
from .incident import (
    EscalationPolicy,
    ImpactCalculator,
    Incident,
    IncidentAuditEvent,
    IncidentAuditLog,
    IncidentContext,
    IncidentControlRequest,
    IncidentEscalator,
    IncidentImpact,
    IncidentManager,
    IncidentSeverity,
    IncidentState,
    RECOVERY_GATE_CHECKS,
    RecoveryCheck,
    RecoveryGate,
    VALID_TRANSITIONS,
    assess_severity,
    build_correlation_key,
    map_alert_severity,
    should_open_incident,
    transition,
)
from .models import (
    OperationalSnapshot,
    ServiceDependency,
    ServiceHealth,
    ServiceIdentity,
    ServiceState,
    TelemetryContext,
)
from .runbook import (
    ApprovalRequest,
    ApprovalWorkflow,
    Checklist,
    ChecklistItem,
    ConditionOperator,
    RECOVERY_CHECKLIST_ITEMS,
    RecoveryGate as RunbookRecoveryGate,
    Runbook,
    RunbookAction,
    RunbookCondition,
    RunbookDefinition,
    RunbookExecution,
    RunbookExecutor,
    RunbookRegistry,
    RunbookSeverity,
    RunbookStep,
    RunbookValidator,
    StepExecutionRecord,
    StepStatus,
    StepType,
    build_recovery_checklist,
    build_standard_runbooks,
    evaluate_condition,
    register_standard_runbooks,
    requires_approval,
)
from .registry import (
    RegisteredService,
    ServiceRegistry,
    validate_dependency,
)
from .snapshot import OperationalSnapshotBuilder
from .telemetry import (
    Counter,
    FORBIDDEN_LABELS,
    Gauge,
    Histogram,
    MetricDefinition,
    MetricRegistry,
    MetricSample,
    MetricType,
    RECOMMENDED_LABELS,
    TelemetryRecorder,
    control_plane_metrics,
    ledger_metrics,
    position_metrics,
    reconciliation_metrics,
    recovery_metrics,
    register_standard_metrics,
    standard_metrics,
    system_gauges,
    trading_metrics,
    venue_metrics,
)

__all__ = [
    "Alert",
    "ApprovalRequest",
    "ApprovalWorkflow",
    "Checklist",
    "ChecklistItem",
    "ConditionOperator",
    "AlertDeduplicator",
    "AlertFingerprint",
    "AlertManager",
    "AlertRule",
    "AlertRuleEvaluator",
    "AlertRouter",
    "AlertSeverity",
    "AlertState",
    "AlertStormProtector",
    "ConditionEvaluator",
    "Counter",
    "EscalationPolicy",
    "FlappingDetector",
    "FORBIDDEN_LABELS",
    "Gauge",
    "Histogram",
    "ImpactCalculator",
    "Incident",
    "IncidentAuditEvent",
    "IncidentAuditLog",
    "IncidentContext",
    "IncidentControlRequest",
    "IncidentEscalator",
    "IncidentImpact",
    "IncidentManager",
    "IncidentSeverity",
    "IncidentState",
    "MetricDefinition",
    "MetricRegistry",
    "MetricSample",
    "MetricType",
    "OperationalSnapshot",
    "OperationalSnapshotBuilder",
    "RECOMMENDED_LABELS",
    "RECOVERY_CHECKLIST_ITEMS",
    "RECOVERY_GATE_CHECKS",
    "RecoveryCheck",
    "RecoveryGate",
    "Runbook",
    "RunbookAction",
    "RunbookCondition",
    "RunbookDefinition",
    "RunbookExecution",
    "RunbookExecutor",
    "RunbookRecoveryGate",
    "RunbookRegistry",
    "RunbookSeverity",
    "RunbookStep",
    "RunbookValidator",
    "RegisteredService",
    "ServiceDependency",
    "ServiceHealth",
    "ServiceHealthMonitor",
    "ServiceIdentity",
    "ServiceRegistry",
    "ServiceState",
    "StepExecutionRecord",
    "StepStatus",
    "StepType",
    "TelemetryContext",
    "TelemetryRecorder",
    "VALID_TRANSITIONS",
    "assess_severity",
    "build_correlation_key",
    "build_recovery_checklist",
    "build_standard_runbooks",
    "evaluate_condition",
    "control_plane_metrics",
    "ledger_metrics",
    "map_alert_severity",
    "position_metrics",
    "reconciliation_metrics",
    "recovery_metrics",
    "register_standard_metrics",
    "register_standard_runbooks",
    "requires_approval",
    "should_open_incident",
    "standard_metrics",
    "standard_rules",
    "system_gauges",
    "trading_metrics",
    "transition",
    "validate_dependency",
    "venue_metrics",
]
