"""
Event types.
"""

from enum import Enum


class EventType(Enum):

    PORTFOLIO_CREATED = "PORTFOLIO_CREATED"

    PORTFOLIO_UPDATED = "PORTFOLIO_UPDATED"

    POSITION_ADDED = "POSITION_ADDED"

    POSITION_REMOVED = "POSITION_REMOVED"

    REBALANCE_TRIGGERED = "REBALANCE_TRIGGERED"

    VALUATION_COMPLETED = "VALUATION_COMPLETED"

    COMPLIANCE_VIOLATION = "COMPLIANCE_VIOLATION"

    AUDIT_LOGGED = "AUDIT_LOGGED"