"""Risk Warning Engine – real-time risk monitoring and alerts."""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class RiskAlert:
    """A risk alert generated by the monitoring engine."""

    level: str  # "info", "warning", "critical"
    message: str
    source: str = ""  # e.g. "exposure", "drawdown", "volatility"
    threshold: float = 0.0
    current_value: float = 0.0

    def to_dict(self) -> dict:
        return {
            "level": self.level,
            "message": self.message,
            "source": self.source,
            "threshold": self.threshold,
            "current_value": self.current_value,
        }


class RiskMonitor:
    """Continuously monitors portfolio risk metrics and emits alerts.

    Checks exposure limits, drawdown thresholds, volatility caps, and
    concentration constraints, producing structured RiskAlert objects.
    """

    def __init__(
        self,
        max_exposure: float = 1.0,
        max_drawdown: float = 0.2,
        max_volatility: float = 0.5,
        max_sector_concentration: float = 0.4,
    ):
        self.max_exposure = max_exposure
        self.max_drawdown = max_drawdown
        self.max_volatility = max_volatility
        self.max_sector_concentration = max_sector_concentration

    def check(
        self,
        exposure: float = 0.0,
        drawdown: float = 0.0,
        volatility: float = 0.0,
        sector_concentration: float = 0.0,
    ) -> List[RiskAlert]:
        """Run all risk checks and return triggered alerts."""
        alerts: List[RiskAlert] = []

        # Exposure check
        if exposure > self.max_exposure:
            alerts.append(
                RiskAlert(
                    level="critical",
                    message=f"Exposure {exposure:.1%} exceeds limit {self.max_exposure:.1%}",
                    source="exposure",
                    threshold=self.max_exposure,
                    current_value=exposure,
                )
            )
        elif exposure > self.max_exposure * 0.8:
            alerts.append(
                RiskAlert(
                    level="warning",
                    message=f"Exposure {exposure:.1%} approaching limit {self.max_exposure:.1%}",
                    source="exposure",
                    threshold=self.max_exposure,
                    current_value=exposure,
                )
            )

        # Drawdown check
        if drawdown > self.max_drawdown:
            alerts.append(
                RiskAlert(
                    level="critical",
                    message=f"Drawdown {drawdown:.1%} exceeds limit {self.max_drawdown:.1%}",
                    source="drawdown",
                    threshold=self.max_drawdown,
                    current_value=drawdown,
                )
            )
        elif drawdown > self.max_drawdown * 0.7:
            alerts.append(
                RiskAlert(
                    level="warning",
                    message=f"Drawdown {drawdown:.1%} approaching limit {self.max_drawdown:.1%}",
                    source="drawdown",
                    threshold=self.max_drawdown,
                    current_value=drawdown,
                )
            )

        # Volatility check
        if volatility > self.max_volatility:
            alerts.append(
                RiskAlert(
                    level="warning",
                    message=f"Volatility {volatility:.1%} exceeds limit {self.max_volatility:.1%}",
                    source="volatility",
                    threshold=self.max_volatility,
                    current_value=volatility,
                )
            )

        # Sector concentration check
        if sector_concentration > self.max_sector_concentration:
            alerts.append(
                RiskAlert(
                    level="warning",
                    message=(
                        f"Portfolio Sector Exposure {sector_concentration:.1%} "
                        f"> {self.max_sector_concentration:.1%}. Risk Increasing."
                    ),
                    source="concentration",
                    threshold=self.max_sector_concentration,
                    current_value=sector_concentration,
                )
            )

        return alerts

    def has_critical(self, alerts: List[RiskAlert]) -> bool:
        """Return True if any alert is at 'critical' level."""
        return any(a.level == "critical" for a in alerts)
