"""Portfolio Rebalancer — drift detection and trade generation."""

import time
import uuid
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class RebalanceMethod(Enum):
    CALENDAR = "calendar"  # Fixed schedule
    THRESHOLD = "threshold"  # Drift-based trigger
    HYBRID = "hybrid"  # Calendar + threshold
    OPPORTUNISTIC = "opportunistic"  # Event-driven
    TAX_AWARE = "tax_aware"  # Tax-loss harvesting
    RISK_DRIVEN = "risk_driven"  # Risk-based trigger


@dataclass
class RebalanceConfig:
    """Configuration for portfolio rebalancing."""

    method: RebalanceMethod = RebalanceMethod.THRESHOLD
    drift_threshold_pct: float = 5.0  # trigger when weight deviates > 5%
    partial_rebalance: bool = False  # only rebalance drifted positions
    min_trade_value: float = 10000.0  # minimum trade size
    max_trades_per_rebalance: int = 50
    allow_short: bool = False
    cash_buffer_pct: float = 1.0  # keep 1% cash for fees
    transaction_cost_bps: float = 10.0  # 10 bps one-way
    market_impact_model: str = "linear"  # linear | square_root | kyle
    preserve_tax_lot: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TargetWeight:
    """Target weight for a single position."""

    symbol: str = ""
    current_weight: float = 0.0
    target_weight: float = 0.0
    drift: float = 0.0
    requires_trade: bool = False

    @property
    def abs_drift(self) -> float:
        return abs(self.drift)

    @property
    def trade_direction(self) -> str:
        if self.drift > 0:
            return "SELL"
        elif self.drift < 0:
            return "BUY"
        return "HOLD"


@dataclass
class Trade:
    """A single trade generated by rebalance."""

    trade_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    symbol: str = ""
    side: str = ""  # BUY | SELL
    quantity: float = 0.0
    price: float = 0.0
    value: float = 0.0
    weight_before: float = 0.0
    weight_after: float = 0.0
    estimated_cost_bps: float = 0.0
    reason: str = ""
    priority: int = 0  # 0=low, 1=normal, 2=high


@dataclass
class TradeList:
    """Ordered list of trades for rebalance execution."""

    list_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    portfolio_id: str = ""
    trades: List[Trade] = field(default_factory=list)
    total_buy_value: float = 0.0
    total_sell_value: float = 0.0
    net_flow: float = 0.0
    estimated_total_cost: float = 0.0
    generated_at: float = field(default_factory=time.time)

    @property
    def trade_count(self) -> int:
        return len(self.trades)

    @property
    def is_cash_neutral(self) -> bool:
        return abs(self.net_flow) < 0.01

    def get_buys(self) -> List[Trade]:
        return [t for t in self.trades if t.side == "BUY"]

    def get_sells(self) -> List[Trade]:
        return [t for t in self.trades if t.side == "SELL"]


@dataclass
class RebalanceResult:
    """Complete result of a rebalance operation."""

    result_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    portfolio_id: str = ""
    method: RebalanceMethod = RebalanceMethod.THRESHOLD
    triggered: bool = False
    trigger_reason: str = ""
    targets: List[TargetWeight] = field(default_factory=list)
    trade_list: Optional[TradeList] = None
    pre_rebalance_nav: float = 0.0
    estimated_post_nav: float = 0.0
    total_drift_sum: float = 0.0
    positions_rebalanced: int = 0
    estimated_turnover_pct: float = 0.0
    warnings: List[str] = field(default_factory=list)
    executed_at: float = field(default_factory=time.time)


class PortfolioRebalancer:
    """Portfolio rebalancer for drift detection and trade generation.

    Supports multiple rebalance methods:
    - Calendar-based (fixed schedule)
    - Threshold-based (drift trigger)
    - Hybrid (calendar + threshold)
    - Opportunistic (event-driven)
    - Tax-aware harvesting
    - Risk-driven rebalancing

    Generates trade lists with cost estimates.
    """

    def __init__(self, config: Optional[RebalanceConfig] = None):
        self.config = config or RebalanceConfig()
        self._results: List[RebalanceResult] = []

    def compute_drift(
        self,
        current_weights: Dict[str, float],
        target_weights: Dict[str, float],
    ) -> List[TargetWeight]:
        """Compute weight drift for all positions."""
        all_symbols = set(list(current_weights.keys()) + list(target_weights.keys()))
        targets = []

        for symbol in all_symbols:
            cw = current_weights.get(symbol, 0.0)
            tw = target_weights.get(symbol, 0.0)
            drift = (cw - tw) * 100  # in percentage points
            requires = abs(drift) > self.config.drift_threshold_pct
            targets.append(TargetWeight(
                symbol=symbol,
                current_weight=cw,
                target_weight=tw,
                drift=drift,
                requires_trade=requires,
            ))

        return sorted(targets, key=lambda x: abs(x.drift), reverse=True)

    def should_rebalance(
        self,
        targets: List[TargetWeight],
        last_rebalance_time: float = 0.0,
        calendar_days: int = 30,
    ) -> Tuple[bool, str]:
        """Determine if rebalancing should be triggered."""
        method = self.config.method

        # Threshold-based check
        if method in (RebalanceMethod.THRESHOLD, RebalanceMethod.HYBRID):
            drifted = [t for t in targets if t.requires_trade]
            if drifted:
                total_drift = sum(t.abs_drift for t in drifted)
                return True, f"Threshold breach: {len(drifted)} positions drifted, total drift {total_drift:.1f}pp"

        # Calendar-based check
        if method in (RebalanceMethod.CALENDAR, RebalanceMethod.HYBRID):
            days_since = (time.time() - last_rebalance_time) / 86400 if last_rebalance_time > 0 else float("inf")
            if days_since >= calendar_days:
                return True, f"Calendar trigger: {days_since:.0f} days since last rebalance"

        return False, "No trigger conditions met"

    def generate_trades(
        self,
        portfolio_id: str,
        targets: List[TargetWeight],
        nav: float,
        prices: Dict[str, float],
    ) -> TradeList:
        """Generate trade list from target weights."""
        trade_list = TradeList(portfolio_id=portfolio_id)
        trades = []
        total_buy = 0.0
        total_sell = 0.0

        for target in targets:
            if not target.requires_trade:
                continue

            price = prices.get(target.symbol, 100.0)
            value = nav * abs(target.drift) / 100.0

            if value < self.config.min_trade_value:
                continue

            if len(trades) >= self.config.max_trades_per_rebalance:
                logger.warning("Max trades (%d) reached for portfolio %s",
                             self.config.max_trades_per_rebalance, portfolio_id)
                break

            side = "SELL" if target.drift > 0 else "BUY"
            quantity = value / price if price > 0 else 0.0
            cost_bps = self.config.transaction_cost_bps + self._estimate_market_impact(value, nav)

            trade = Trade(
                symbol=target.symbol,
                side=side,
                quantity=quantity,
                price=price,
                value=value,
                weight_before=target.current_weight,
                weight_after=target.target_weight,
                estimated_cost_bps=cost_bps,
                reason=f"Rebalance: {'overweight' if side == 'SELL' else 'underweight'} "
                       f"by {abs(target.drift):.2f}pp",
                priority=1 if abs(target.drift) > self.config.drift_threshold_pct * 2 else 0,
            )

            if side == "BUY":
                total_buy += value
            else:
                total_sell += value

            trades.append(trade)

        trade_list.trades = trades
        trade_list.total_buy_value = total_buy
        trade_list.total_sell_value = total_sell
        trade_list.net_flow = total_sell - total_buy
        trade_list.estimated_total_cost = sum(
            t.value * t.estimated_cost_bps / 10000 for t in trades
        )

        logger.info(
            "Generated %d trades for portfolio %s (buy=%.2f, sell=%.2f, net=%.2f)",
            len(trades), portfolio_id, total_buy, total_sell, trade_list.net_flow,
        )
        return trade_list

    def _estimate_market_impact(self, trade_value: float, nav: float) -> float:
        """Estimate market impact in bps."""
        if nav <= 0:
            return 0.0
        participation_rate = trade_value / nav

        if self.config.market_impact_model == "square_root":
            return 15.0 * math.sqrt(participation_rate) * 100  # bps
        else:
            # Linear model
            return 10.0 * participation_rate * 100  # bps

    def rebalance(
        self,
        portfolio_id: str,
        current_weights: Dict[str, float],
        target_weights: Dict[str, float],
        nav: float,
        prices: Dict[str, float],
        last_rebalance_time: float = 0.0,
    ) -> RebalanceResult:
        """Execute full rebalance workflow: detect drift → decide → generate trades."""
        import math as _math
        global math
        math = _math

        # Step 1: Compute drift
        targets = self.compute_drift(current_weights, target_weights)

        # Step 2: Check if rebalance needed
        triggered, reason = self.should_rebalance(targets, last_rebalance_time)
        if not triggered:
            result = RebalanceResult(
                portfolio_id=portfolio_id,
                method=self.config.method,
                triggered=False,
                trigger_reason=reason,
                targets=targets,
                pre_rebalance_nav=nav,
            )
            self._results.append(result)
            return result

        # Step 3: Generate trades
        trade_list = self.generate_trades(portfolio_id, targets, nav, prices)

        # Step 4: Calculate metrics
        drifted_positions = [t for t in targets if t.requires_trade]
        total_drift = sum(t.abs_drift for t in drifted_positions)
        turnover = sum(
            abs(t.drift) / 100.0 for t in drifted_positions
        ) / 2.0 if drifted_positions else 0.0
        estimated_cost = sum(
            t.estimated_cost_bps for t in (trade_list.trades if trade_list else [])
        )

        result = RebalanceResult(
            portfolio_id=portfolio_id,
            method=self.config.method,
            triggered=True,
            trigger_reason=reason,
            targets=targets,
            trade_list=trade_list,
            pre_rebalance_nav=nav,
            estimated_post_nav=nav - (trade_list.estimated_total_cost if trade_list else 0.0),
            total_drift_sum=total_drift,
            positions_rebalanced=len(drifted_positions),
            estimated_turnover_pct=turnover * 100,
            warnings=[],
        )

        # Warnings
        if trade_list and trade_list.net_flow > nav * 0.01:
            result.warnings.append("Significant net flow imbalance")

        self._results.append(result)
        return result

    def get_results(
        self, portfolio_id: Optional[str] = None, limit: int = 50
    ) -> List[RebalanceResult]:
        results = self._results
        if portfolio_id:
            results = [r for r in results if r.portfolio_id == portfolio_id]
        return results[-limit:]

    def get_latest_result(self, portfolio_id: Optional[str] = None) -> Optional[RebalanceResult]:
        results = self.get_results(portfolio_id, limit=1)
        return results[0] if results else None

    def get_summary(self, portfolio_id: Optional[str] = None) -> Dict[str, Any]:
        results = self.get_results(portfolio_id)
        if not results:
            return {"total_rebalances": 0}

        triggered = sum(1 for r in results if r.triggered)
        total_turnover = sum(r.estimated_turnover_pct for r in results)
        return {
            "total_rebalances": len(results),
            "triggered_rebalances": triggered,
            "trigger_rate_pct": triggered / len(results) * 100,
            "avg_turnover_pct": total_turnover / len(results) if results else 0.0,
            "method": self.config.method.value,
            "threshold_pct": self.config.drift_threshold_pct,
        }
