"""Alpha Discovery Engine.

Automatically discovers alpha factors by combining base factor
templates with operators across feature groups.
"""

from __future__ import annotations

import itertools
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np


class Operator(str, Enum):
    """Operators for combining factors."""

    ADD = "+"
    SUB = "-"
    MUL = "*"
    DIV = "/"
    RANK_ADD = "rank_add"
    RANK_MUL = "rank_mul"
    ZSCORE_ADD = "zscore_add"
    CROSS_SECTIONAL = "cross_sectional"


@dataclass
class FactorTemplate:
    """A base factor template for alpha discovery.

    Attributes:
        name: Factor name.
        category: Factor category (momentum, volatility, etc.).
        transform: Optional transformation to apply.
        params: Parameters for the factor.
        tags: Searchable tags.
    """

    name: str
    category: str = "uncategorized"
    transform: str = "identity"
    params: Dict[str, Any] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)


@dataclass
class AlphaCandidate:
    """A candidate alpha factor generated by the discovery engine.

    Attributes:
        name: Generated alpha name.
        expression: Human-readable expression.
        factors: Constituent factor names.
        operators: Operators used.
        score: Quality score from evaluation.
        metrics: Detailed evaluation metrics.
        discovered_at: Timestamp.
    """

    name: str
    expression: str
    factors: List[str] = field(default_factory=list)
    operators: List[Operator] = field(default_factory=list)
    score: float = 0.0
    metrics: Dict[str, float] = field(default_factory=dict)
    discovered_at: float = field(default_factory=time.time)


class AlphaDiscovery:
    """Automated Alpha Factor Discovery Engine.

    Generates candidate alpha factors by combining base factor
    templates with mathematical operators and evaluating them.
    """

    # ---- init ----

    def __init__(self, seed: int = 42) -> None:
        self._templates: Dict[str, FactorTemplate] = {}
        self._candidates: List[AlphaCandidate] = []
        self._operators: List[Operator] = [
            Operator.ADD, Operator.SUB, Operator.MUL, Operator.DIV,
            Operator.RANK_ADD, Operator.RANK_MUL,
        ]
        self.rng = np.random.RandomState(seed)

    # ---- template management ----

    def register_template(self, template: FactorTemplate) -> None:
        self._templates[template.name] = template

    def register_templates(self, templates: List[FactorTemplate]) -> None:
        for t in templates:
            self.register_template(t)

    def get_template(self, name: str) -> FactorTemplate:
        if name not in self._templates:
            raise KeyError(f"Factor template '{name}' not found")
        return self._templates[name]

    def list_templates(self, category: Optional[str] = None) -> List[FactorTemplate]:
        if category:
            return [t for t in self._templates.values() if t.category == category]
        return list(self._templates.values())

    # ---- discovery ----

    def discover(
        self,
        data: Dict[str, List[float]],
        eval_fn: Callable[[str, List[float]], Dict[str, float]],
        n_candidates: int = 100,
        max_depth: int = 2,
        categories: Optional[List[str]] = None,
    ) -> List[AlphaCandidate]:
        """Run alpha discovery.

        Args:
            data: factor_name -> values mapping.
            eval_fn: (alpha_name, alpha_values) -> metrics dict.
            n_candidates: Max candidates to generate.
            max_depth: Max number of factors to combine.
            categories: Limit to specific template categories.

        Returns:
            List of AlphaCandidate sorted by score descending.
        """
        factor_names = list(data.keys())
        if len(factor_names) < 2:
            return []

        templates = self.list_templates()
        if categories:
            templates = [t for t in templates if t.category in categories]
        template_names = [t.name for t in templates if t.name in data]

        self._candidates = []

        # Depth 1: Individual factors
        for name in factor_names[: min(len(factor_names), n_candidates)]:
            if name in data:
                metrics = eval_fn(name, data[name])
                score = metrics.get("composite", metrics.get("sharpe", 0.0))
                candidate = AlphaCandidate(
                    name=f"alpha_{name}",
                    expression=name,
                    factors=[name],
                    score=score,
                    metrics=metrics,
                )
                self._candidates.append(candidate)

        # Depth 2: Pair combinations
        pairs = list(itertools.combinations(factor_names, 2))
        self.rng.shuffle(pairs)
        n_pairs = min(len(pairs), n_candidates - len(self._candidates))

        for f1, f2 in pairs[:n_pairs]:
            if f1 not in data or f2 not in data:
                continue
            for op in self._operators[:4]:  # basic ops
                combined = self._apply_op(data[f1], data[f2], op)
                if combined is None:
                    continue
                name = f"alpha_{f1}_{op.value}_{f2}"
                metrics = eval_fn(name, combined)
                score = metrics.get("composite", metrics.get("sharpe", 0.0))
                candidate = AlphaCandidate(
                    name=name,
                    expression=f"{f1} {op.value} {f2}",
                    factors=[f1, f2],
                    operators=[op],
                    score=score,
                    metrics=metrics,
                )
                self._candidates.append(candidate)

                if len(self._candidates) >= n_candidates:
                    break
            if len(self._candidates) >= n_candidates:
                break

        # Depth 3: Cross-sectional / rank combinations
        if max_depth >= 3 and len(self._candidates) < n_candidates and len(factor_names) >= 3:
            triples = list(itertools.combinations(factor_names, 3))
            self.rng.shuffle(triples)
            n_triple = min(len(triples), n_candidates - len(self._candidates))
            for f1, f2, f3 in triples[:n_triple]:
                if not all(f in data for f in (f1, f2, f3)):
                    continue
                combined = self._combine_rank_mul(data[f1], data[f2], data[f3])
                if combined is None:
                    continue
                name = f"alpha_{f1}_x_{f2}_x_{f3}"
                metrics = eval_fn(name, combined)
                score = metrics.get("composite", metrics.get("sharpe", 0.0))
                candidate = AlphaCandidate(
                    name=name,
                    expression=f"rank({f1} * {f2} * {f3})",
                    factors=[f1, f2, f3],
                    operators=[Operator.RANK_MUL],
                    score=score,
                    metrics=metrics,
                )
                self._candidates.append(candidate)

        # Sort by score descending
        self._candidates.sort(key=lambda c: c.score, reverse=True)
        return self._candidates

    def top_candidates(self, n: int = 10) -> List[AlphaCandidate]:
        return self._candidates[:n]

    # ---- operators ----

    @staticmethod
    def _apply_op(a: List[float], b: List[float], op: Operator) -> Optional[List[float]]:
        n = min(len(a), len(b))
        if n == 0:
            return None
        result: List[float] = []
        a_arr = np.array(a[:n], dtype=np.float64)
        b_arr = np.array(b[:n], dtype=np.float64)
        mask = ~np.isnan(a_arr) & ~np.isnan(b_arr)

        if op == Operator.ADD:
            result = (a_arr + b_arr).tolist()
        elif op == Operator.SUB:
            result = (a_arr - b_arr).tolist()
        elif op == Operator.MUL:
            result = (a_arr * b_arr).tolist()
        elif op == Operator.DIV:
            with np.errstate(divide="ignore", invalid="ignore"):
                result = np.where(b_arr != 0, a_arr / b_arr, np.nan).tolist()
        elif op == Operator.RANK_ADD:
            from scipy.stats import rankdata
            ra = rankdata(a_arr[~np.isnan(a_arr)], method="average")
            rb = rankdata(b_arr[~np.isnan(b_arr)], method="average")
            result = (ra / len(ra) + rb / len(rb)).tolist()
        elif op == Operator.RANK_MUL:
            from scipy.stats import rankdata
            ra = rankdata(a_arr[~np.isnan(a_arr)], method="average")
            rb = rankdata(b_arr[~np.isnan(b_arr)], method="average")
            result = (ra / len(ra) * rb / len(rb)).tolist()
        elif op == Operator.ZSCORE_ADD:
            za = (a_arr - np.nanmean(a_arr)) / (np.nanstd(a_arr) or 1)
            zb = (b_arr - np.nanmean(b_arr)) / (np.nanstd(b_arr) or 1)
            result = (za + zb).tolist()
        else:
            result = a[:n]

        return result

    @staticmethod
    def _combine_rank_mul(a: List[float], b: List[float], c: List[float]) -> Optional[List[float]]:
        n = min(len(a), len(b), len(c))
        if n == 0:
            return None
        from scipy.stats import rankdata
        a_arr = np.array(a[:n], dtype=np.float64)
        b_arr = np.array(b[:n], dtype=np.float64)
        c_arr = np.array(c[:n], dtype=np.float64)
        ra = rankdata(a_arr, method="average") / n
        rb = rankdata(b_arr, method="average") / n
        rc = rankdata(c_arr, method="average") / n
        return (ra * rb * rc).tolist()

    # ---- stats ----

    def candidate_count(self) -> int:
        return len(self._candidates)

    def best_score(self) -> float:
        return self._candidates[0].score if self._candidates else 0.0
