"""Rebalance Executor — executes rebalance orders with multiple execution modes."""

import time
import uuid
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


class ExecutionMode(Enum):
    PAPER = "paper"             # Simulated execution
    LIVE = "live"               # Real execution
    DRY_RUN = "dry_run"         # Generate orders only, no execution
    TWAP = "twap"               # Time-weighted average price
    VWAP = "vwap"               # Volume-weighted average price
    SMART = "smart"             # Smart order routing
    ICEBERG = "iceberg"         # Hidden quantity execution


class OrderStatus(Enum):
    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class OrderSide(Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


@dataclass
class ExecutorConfig:
    """Configuration for rebalance executor."""

    execution_mode: ExecutionMode = ExecutionMode.PAPER
    max_slippage_pct: float = 0.5
    max_market_impact_pct: float = 1.0
    order_timeout_seconds: int = 300
    retry_attempts: int = 3
    retry_delay_seconds: int = 5
    batch_size: int = 10
    concurrent_orders: int = 5
    min_order_value: float = 1000.0
    validate_before_execute: bool = True
    enable_circuit_breaker: bool = True
    circuit_breaker_threshold_pct: float = 5.0  # halt if loss > 5%
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RebalanceOrder:
    """A single order generated during rebalance."""

    order_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    portfolio_id: str = ""
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    limit_price: Optional[float] = None
    target_weight: float = 0.0
    current_weight: float = 0.0
    weight_delta: float = 0.0
    estimated_value: float = 0.0
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    avg_fill_price: float = 0.0
    slippage_pct: float = 0.0
    commission: float = 0.0
    created_at: float = field(default_factory=time.time)
    executed_at: float = 0.0
    error_message: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_filled(self) -> bool:
        return self.status == OrderStatus.FILLED

    @property
    def fill_rate(self) -> float:
        return (self.filled_quantity / self.quantity * 100) if self.quantity > 0 else 0.0

    @property
    def execution_value(self) -> float:
        return self.filled_quantity * self.avg_fill_price


@dataclass
class ExecutionResult:
    """Result of a rebalance execution batch."""

    result_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    portfolio_id: str = ""
    execution_mode: ExecutionMode = ExecutionMode.PAPER
    total_orders: int = 0
    filled_orders: int = 0
    cancelled_orders: int = 0
    rejected_orders: int = 0
    total_value: float = 0.0
    total_commission: float = 0.0
    total_slippage: float = 0.0
    execution_time_seconds: float = 0.0
    status: str = "completed"
    orders: List[RebalanceOrder] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)

    @property
    def fill_rate_pct(self) -> float:
        return (self.filled_orders / self.total_orders * 100) if self.total_orders > 0 else 0.0

    @property
    def total_executed_value(self) -> float:
        return sum(o.execution_value for o in self.orders if o.is_filled)


class RebalanceExecutor:
    """Executes rebalance orders generated by the rebalancer.

    Supports multiple execution modes: PAPER, LIVE, DRY_RUN, TWAP, VWAP.
    Manages order lifecycle, slippage tracking, and circuit breakers.
    """

    def __init__(self, config: Optional[ExecutorConfig] = None):
        self.config = config or ExecutorConfig()
        self._orders: Dict[str, RebalanceOrder] = {}
        self._results: List[ExecutionResult] = []
        self._order_handler: Optional[Callable] = None
        self._circuit_broken: bool = False
        self._cumulative_loss: float = 0.0

    def set_order_handler(self, handler: Callable[[RebalanceOrder], Dict[str, Any]]) -> None:
        """Set custom order handler for live execution integration."""
        self._order_handler = handler

    def execute_orders(
        self,
        portfolio_id: str,
        orders: List[RebalanceOrder],
    ) -> ExecutionResult:
        """Execute a batch of rebalance orders."""
        start_time = time.time()
        result = ExecutionResult(
            portfolio_id=portfolio_id,
            execution_mode=self.config.execution_mode,
            total_orders=len(orders),
            orders=orders,
        )

        if self._circuit_broken:
            result.status = "circuit_breaker"
            result.errors.append("Circuit breaker active — execution halted")
            self._results.append(result)
            return result

        for order in orders:
            if self.config.validate_before_execute:
                validation_error = self._validate_order(order)
                if validation_error:
                    order.status = OrderStatus.REJECTED
                    order.error_message = validation_error
                    result.rejected_orders += 1
                    result.errors.append(f"{order.symbol}: {validation_error}")
                    continue

            self._execute_single(order, result)

        result.execution_time_seconds = time.time() - start_time
        result.filled_orders = sum(1 for o in orders if o.is_filled)
        result.cancelled_orders = sum(1 for o in orders if o.status == OrderStatus.CANCELLED)
        result.rejected_orders = sum(1 for o in orders if o.status == OrderStatus.REJECTED)
        result.total_commission = sum(o.commission for o in orders)
        result.total_slippage = sum(abs(o.slippage_pct) for o in orders if o.is_filled) / max(
            result.filled_orders, 1
        )
        result.total_value = sum(o.execution_value for o in orders if o.is_filled)

        self._results.append(result)
        logger.info(
            "Execution result for %s: %d/%d filled (%.1f%%), time=%.2fs",
            portfolio_id,
            result.filled_orders,
            result.total_orders,
            result.fill_rate_pct,
            result.execution_time_seconds,
        )
        return result

    def _execute_single(self, order: RebalanceOrder, result: ExecutionResult) -> None:
        """Execute a single order based on execution mode."""
        order.status = OrderStatus.SUBMITTED

        if self.config.execution_mode == ExecutionMode.DRY_RUN:
            order.status = OrderStatus.FILLED
            order.filled_quantity = order.quantity
            order.avg_fill_price = order.limit_price or 100.0
            order.executed_at = time.time()
            return

        if self.config.execution_mode == ExecutionMode.PAPER:
            # Simulate execution with slippage
            import random
            base_price = order.limit_price or 100.0
            slippage = random.uniform(-self.config.max_slippage_pct / 100,
                                     self.config.max_slippage_pct / 100)
            order.avg_fill_price = base_price * (1 + slippage)
            order.slippage_pct = slippage * 100
            order.filled_quantity = order.quantity
            order.commission = order.quantity * order.avg_fill_price * 0.0003  # 3 bps
            order.status = OrderStatus.FILLED
            order.executed_at = time.time()
            return

        if self._order_handler:
            # Delegate to external handler for live execution
            try:
                handler_result = self._order_handler(order)
                order.status = OrderStatus(handler_result.get("status", "filled"))
                order.filled_quantity = handler_result.get("filled_quantity", order.quantity)
                order.avg_fill_price = handler_result.get("avg_fill_price", 0.0)
                order.executed_at = time.time()
            except Exception as e:
                order.status = OrderStatus.REJECTED
                order.error_message = str(e)
                result.errors.append(f"{order.symbol}: {e}")

    def _validate_order(self, order: RebalanceOrder) -> Optional[str]:
        """Validate an order before execution."""
        if order.quantity <= 0:
            return "Invalid quantity"
        estimated_value = order.quantity * (order.limit_price or 100.0)
        if estimated_value < self.config.min_order_value:
            return f"Order value {estimated_value} below minimum {self.config.min_order_value}"
        order.estimated_value = estimated_value
        return None

    def get_order(self, order_id: str) -> Optional[RebalanceOrder]:
        return self._orders.get(order_id)

    def get_orders_by_portfolio(self, portfolio_id: str) -> List[RebalanceOrder]:
        return [o for o in self._orders.values() if o.portfolio_id == portfolio_id]

    def get_results(
        self, portfolio_id: Optional[str] = None, limit: int = 50
    ) -> List[ExecutionResult]:
        results = self._results
        if portfolio_id:
            results = [r for r in results if r.portfolio_id == portfolio_id]
        return results[-limit:]

    def cancel_order(self, order_id: str) -> bool:
        order = self._orders.get(order_id)
        if order and order.status in (OrderStatus.PENDING, OrderStatus.SUBMITTED):
            order.status = OrderStatus.CANCELLED
            return True
        return False

    def cancel_all_orders(self, portfolio_id: str) -> int:
        count = 0
        for order in self._orders.values():
            if order.portfolio_id == portfolio_id:
                if self.cancel_order(order.order_id):
                    count += 1
        return count

    def check_circuit_breaker(self, daily_pnl: float, nav: float) -> bool:
        """Check if circuit breaker should be triggered."""
        if not self.config.enable_circuit_breaker:
            return False
        if nav <= 0:
            return False
        loss_pct = abs(daily_pnl) / nav * 100
        if loss_pct > self.config.circuit_breaker_threshold_pct:
            self._circuit_broken = True
            logger.warning(
                "Circuit breaker triggered! Loss: %.2f%% exceeds threshold %.2f%%",
                loss_pct, self.config.circuit_breaker_threshold_pct,
            )
            return True
        return False

    def reset_circuit_breaker(self) -> None:
        self._circuit_broken = False
        self._cumulative_loss = 0.0

    def get_execution_summary(self, portfolio_id: Optional[str] = None) -> Dict[str, Any]:
        results = self.get_results(portfolio_id) if portfolio_id else self._results
        if not results:
            return {"total_executions": 0}

        total_orders = sum(r.total_orders for r in results)
        total_filled = sum(r.filled_orders for r in results)
        total_value = sum(r.total_value for r in results)
        avg_fill_rate = (total_filled / total_orders * 100) if total_orders > 0 else 0.0
        avg_exec_time = sum(r.execution_time_seconds for r in results) / len(results)

        return {
            "total_executions": len(results),
            "total_orders": total_orders,
            "total_filled": total_filled,
            "total_value": total_value,
            "avg_fill_rate_pct": avg_fill_rate,
            "avg_execution_time_seconds": avg_exec_time,
            "execution_mode": self.config.execution_mode.value,
            "circuit_breaker_active": self._circuit_broken,
        }
