"""AI Controller — Command and control for the AI Platform.

Manages AI operation routing, decision arbitration, mode switching,
and state transitions. Serves as the command layer between AI intent
and platform execution.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .ai_platform import AIPlatformConfig, AIPlatformMode

logger = logging.getLogger(__name__)


class AIControllerState(Enum):
    """Controller state machine."""

    IDLE = "idle"
    PROCESSING = "processing"
    WAITING_APPROVAL = "waiting_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTING = "executing"
    COMPLETED = "completed"
    ERROR = "error"
    ROLLING_BACK = "rolling_back"


@dataclass
class AISignal:
    """A trading signal generated by AI."""

    signal_id: str
    symbol: str
    direction: str  # BUY, SELL, HOLD
    strength: float  # 0.0 to 1.0
    confidence: float  # 0.0 to 1.0
    source_agent: str
    source_model: str
    source_features: List[str]
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    expiry: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AIDecision:
    """An AI-generated decision that may lead to action."""

    decision_id: str
    state: AIControllerState = AIControllerState.IDLE
    signal: Optional[AISignal] = None
    prediction: Optional[Dict[str, Any]] = None
    context: Optional[Dict[str, Any]] = None
    guards_passed: List[str] = field(default_factory=list)
    guards_failed: List[Dict[str, str]] = field(default_factory=list)
    approval_id: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class AIController:
    """AI Controller — orchestrates command flow between AI and trading.

    The controller enforces the principle:
        AI ≠ Execution Authority

    AI generates signals and predictions, but execution must pass through
    guards, risk, and approval before reaching OMS/EMS.

    Flow:
        AI Signal → Decision Guard → Risk Check → Approval → OMS → Execution
    """

    def __init__(self, config: "AIPlatformConfig") -> None:
        self.config = config
        self._decisions: Dict[str, AIDecision] = {}
        self._handlers: Dict[str, List[Callable]] = {}
        self._pending_approvals: Dict[str, asyncio.Event] = {}
        self._state = AIControllerState.IDLE

    async def start(self) -> None:
        """Start the AI Controller."""
        logger.info("AI Controller starting (mode=%s)", self.config.mode.value)
        self._state = AIControllerState.IDLE
        logger.info("AI Controller ready")

    async def stop(self) -> None:
        """Stop the AI Controller."""
        logger.info("AI Controller stopping")
        self._state = AIControllerState.IDLE
        self._decisions.clear()
        self._pending_approvals.clear()
        logger.info("AI Controller stopped")

    # ------------------------------------------------------------------
    # Decision Lifecycle
    # ------------------------------------------------------------------

    async def create_decision(
        self,
        signal: Optional[AISignal] = None,
        prediction: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> AIDecision:
        """Create a new AI decision for processing."""
        self._state = AIControllerState.PROCESSING

        decision = AIDecision(
            decision_id=f"ai_dec_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}",
            state=AIControllerState.IDLE,
            signal=signal,
            prediction=prediction,
            context=context,
        )

        self._decisions[decision.decision_id] = decision
        logger.info(
            "Decision created: %s (signal=%s, direction=%s)",
            decision.decision_id,
            signal.signal_id if signal else "none",
            signal.direction if signal else "N/A",
        )
        return decision

    async def progress_decision(
        self,
        decision_id: str,
        new_state: AIControllerState,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> AIDecision:
        """Progress a decision to a new state."""
        decision = self._decisions.get(decision_id)
        if not decision:
            raise ValueError(f"Decision not found: {decision_id}")

        valid_transitions = self._valid_transitions(decision.state)
        if new_state not in valid_transitions:
            raise ValueError(
                f"Invalid transition: {decision.state.value} → {new_state.value}"
            )

        decision.state = new_state
        decision.updated_at = datetime.now(timezone.utc)
        if metadata:
            if decision.context is None:
                decision.context = {}
            decision.context.update(metadata)

        # Notify handlers
        await self._notify_handlers(decision_id, new_state, decision)

        logger.debug(
            "Decision %s: %s → %s",
            decision_id,
            decision.state.value,
            new_state.value,
        )
        return decision

    def _valid_transitions(self, current: AIControllerState) -> List[AIControllerState]:
        """Get valid state transitions."""
        transitions = {
            AIControllerState.IDLE: [
                AIControllerState.PROCESSING,
                AIControllerState.ERROR,
            ],
            AIControllerState.PROCESSING: [
                AIControllerState.WAITING_APPROVAL,
                AIControllerState.APPROVED,
                AIControllerState.REJECTED,
                AIControllerState.ERROR,
            ],
            AIControllerState.WAITING_APPROVAL: [
                AIControllerState.APPROVED,
                AIControllerState.REJECTED,
            ],
            AIControllerState.APPROVED: [
                AIControllerState.EXECUTING,
                AIControllerState.ERROR,
                AIControllerState.ROLLING_BACK,
            ],
            AIControllerState.EXECUTING: [
                AIControllerState.COMPLETED,
                AIControllerState.ERROR,
                AIControllerState.ROLLING_BACK,
            ],
            AIControllerState.ERROR: [
                AIControllerState.IDLE,
                AIControllerState.ROLLING_BACK,
            ],
            AIControllerState.ROLLING_BACK: [
                AIControllerState.IDLE,
                AIControllerState.ERROR,
            ],
            AIControllerState.REJECTED: [AIControllerState.IDLE],
            AIControllerState.COMPLETED: [AIControllerState.IDLE],
        }
        return transitions.get(current, [])

    # ------------------------------------------------------------------
    # Guard Integration
    # ------------------------------------------------------------------

    async def apply_guards(
        self,
        decision_id: str,
        guard_results: List[Dict[str, Any]],
    ) -> AIDecision:
        """Apply guard check results to a decision."""
        decision = self._decisions.get(decision_id)
        if not decision:
            raise ValueError(f"Decision not found: {decision_id}")

        for result in guard_results:
            guard_name = result.get("guard", "unknown")
            if result.get("passed", False):
                decision.guards_passed.append(guard_name)
            else:
                decision.guards_failed.append({
                    "guard": guard_name,
                    "reason": result.get("reason", "Unknown rejection"),
                })

        if decision.guards_failed:
            await self.progress_decision(decision_id, AIControllerState.REJECTED)
        else:
            await self.progress_decision(decision_id, AIControllerState.APPROVED)

        return decision

    # ------------------------------------------------------------------
    # Approval Management
    # ------------------------------------------------------------------

    async def request_approval(self, decision_id: str) -> str:
        """Request human or automated approval for a decision."""
        decision = self._decisions.get(decision_id)
        if not decision:
            raise ValueError(f"Decision not found: {decision_id}")

        await self.progress_decision(decision_id, AIControllerState.WAITING_APPROVAL)

        approval_id = f"apr_{decision_id}"
        decision.approval_id = approval_id
        self._pending_approvals[approval_id] = asyncio.Event()

        logger.info("Approval requested: %s for decision %s", approval_id, decision_id)
        return approval_id

    async def approve(self, approval_id: str, reason: str = "") -> AIDecision:
        """Approve a pending decision."""
        decision = self._find_by_approval(approval_id)
        if not decision:
            raise ValueError(f"Approval not found: {approval_id}")

        event = self._pending_approvals.get(approval_id)
        if event:
            event.set()

        await self.progress_decision(
            decision.decision_id,
            AIControllerState.APPROVED,
            metadata={"approval_reason": reason},
        )
        logger.info("Approved: %s - %s", approval_id, reason)
        return decision

    async def reject(self, approval_id: str, reason: str = "") -> AIDecision:
        """Reject a pending decision."""
        decision = self._find_by_approval(approval_id)
        if not decision:
            raise ValueError(f"Approval not found: {approval_id}")

        event = self._pending_approvals.get(approval_id)
        if event:
            event.clear()

        await self.progress_decision(
            decision.decision_id,
            AIControllerState.REJECTED,
            metadata={"rejection_reason": reason},
        )
        logger.info("Rejected: %s - %s", approval_id, reason)
        return decision

    # ------------------------------------------------------------------
    # Event Handling
    # ------------------------------------------------------------------

    def on_state_change(
        self,
        state: AIControllerState,
        handler: Callable,
    ) -> None:
        """Register a handler for state changes."""
        key = f"state:{state.value}"
        if key not in self._handlers:
            self._handlers[key] = []
        self._handlers[key].append(handler)

    async def _notify_handlers(
        self,
        decision_id: str,
        new_state: AIControllerState,
        decision: AIDecision,
    ) -> None:
        """Notify all registered handlers of a state change."""
        key = f"state:{new_state.value}"
        handlers = self._handlers.get(key, [])
        for handler in handlers:
            try:
                if asyncio.iscoroutinefunction(handler):
                    await handler(decision_id, decision)
                else:
                    handler(decision_id, decision)
            except Exception as exc:
                logger.error("Handler error for %s: %s", key, exc)

    def _find_by_approval(self, approval_id: str) -> Optional[AIDecision]:
        """Find a decision by its approval ID."""
        for decision in self._decisions.values():
            if decision.approval_id == approval_id:
                return decision
        return None

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def get_decision(self, decision_id: str) -> Optional[AIDecision]:
        """Get a decision by ID."""
        return self._decisions.get(decision_id)

    def get_active_decisions(self) -> List[AIDecision]:
        """Get all non-terminal decisions."""
        terminal = {AIControllerState.COMPLETED, AIControllerState.REJECTED}
        return [d for d in self._decisions.values() if d.state not in terminal]

    # ------------------------------------------------------------------
    # Health
    # ------------------------------------------------------------------

    async def health(self) -> Dict[str, Any]:
        """Controller health status."""
        total = len(self._decisions)
        by_state: Dict[str, int] = {}
        for d in self._decisions.values():
            by_state[d.state.value] = by_state.get(d.state.value, 0) + 1

        return {
            "state": self._state.value,
            "total_decisions": total,
            "decisions_by_state": by_state,
            "pending_approvals": len(self._pending_approvals),
            "approvals_awaiting": sum(
                1 for e in self._pending_approvals.values() if not e.is_set()
            ),
        }
