"""IncidentAuditEventType — every auditable action in the incident control loop.

Every key action in the incident system must produce an immutable audit event
(spec section 2).  The enum centralises the vocabulary so recorders, timelines
and metrics all speak the same language.
"""

from enum import Enum


class IncidentAuditEventType(str, Enum):
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_UPDATED = "INCIDENT_UPDATED"

    INCIDENT_ACKNOWLEDGED = "INCIDENT_ACKNOWLEDGED"
    INCIDENT_ESCALATED = "INCIDENT_ESCALATED"

    COMMAND_CREATED = "COMMAND_CREATED"
    COMMAND_APPROVED = "COMMAND_APPROVED"
    COMMAND_REJECTED = "COMMAND_REJECTED"

    MITIGATION_STARTED = "MITIGATION_STARTED"
    MITIGATION_COMPLETED = "MITIGATION_COMPLETED"
    MITIGATION_FAILED = "MITIGATION_FAILED"

    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"

    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    INCIDENT_REOPENED = "INCIDENT_REOPENED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"

    POSTMORTEM_CREATED = "POSTMORTEM_CREATED"
    POSTMORTEM_COMPLETED = "POSTMORTEM_COMPLETED"

    REMEDIATION_CREATED = "REMEDIATION_CREATED"
    REMEDIATION_COMPLETED = "REMEDIATION_COMPLETED"
