"""Strategy Runner — unified strategy execution for event-driven backtesting.

Generates trading signals from market data, applies risk filters,
and creates orders — bridging research strategies with live execution
through a consistent interface.

Flow::

    Market Data → Signal Generation → Risk Filter → Order Generation → Execution
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional
from uuid import uuid4

from .backtest_context import BacktestContext
from .backtest_registry import BacktestRegistry
from .event_queue import BacktestEvent, EventPriority

logger = logging.getLogger(__name__)


class SignalType(str, Enum):
    """Trading signal type."""

    BUY = "buy"
    SELL = "sell"
    SHORT = "short"
    COVER = "cover"
    HOLD = "hold"
    CLOSE = "close"


class OrderGenerationMode(str, Enum):
    """Order generation strategy."""

    TARGET_WEIGHT = "target_weight"  # rebalance to target weights
    SIGNAL_BASED = "signal_based"  # generate orders from raw signals
    DELTA_BASED = "delta_based"  # only adjust differences


@dataclass
class TradingSignal:
    """A trading signal generated by a strategy."""

    signal_id: str = field(default_factory=lambda: str(uuid4()))
    symbol: str = ""
    signal_type: SignalType = SignalType.HOLD
    strength: float = 0.0  # -1.0 to 1.0 (negative = sell/short)
    target_weight: Optional[float] = None  # for target-weight strategies
    confidence: float = 1.0  # 0.0 to 1.0
    strategy_name: str = ""
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength,
            "target_weight": self.target_weight,
            "confidence": self.confidence,
            "strategy_name": self.strategy_name,
            "reason": self.reason,
            "metadata": self.metadata,
        }


class StrategyRunner:
    """Unified strategy execution for backtesting.

    Responsibilities:
    * Bridge registered strategies with event-driven execution
    * Generate signals from market data
    * Apply risk filters (position limits, universe constraints)
    * Convert signals to executable orders
    * Maintain consistent interface with live trading runtime
    """

    def __init__(
        self,
        ctx: BacktestContext,
        registry: BacktestRegistry,
        order_mode: OrderGenerationMode = OrderGenerationMode.SIGNAL_BASED,
    ) -> None:
        self._ctx = ctx
        self._registry = registry
        self._order_mode = order_mode
        self._strategy: Optional[Any] = None
        self._signal_generators: List[Callable] = []
        self._risk_filters: List[Callable] = []
        self._order_generator: Optional[Callable] = None
        self._signals: List[TradingSignal] = []
        self._current_positions: Dict[str, Dict[str, Any]] = {}

    # ── initialization ─────────────────────────────────────────────────────

    async def set_strategy(self, strategy: Any) -> None:
        """Set the trading strategy instance."""
        self._strategy = strategy
        logger.info("Strategy set: %s", getattr(strategy, "__class__.__name__", "unknown"))

    def add_signal_generator(self, generator: Callable) -> None:
        """Add a signal generator function.

        Args:
            generator: Callable(market_data, ctx) → List[TradingSignal].
        """
        self._signal_generators.append(generator)

    def add_risk_filter(self, filter_fn: Callable) -> None:
        """Add a risk filter function.

        Args:
            filter_fn: Callable(signal, portfolio, ctx) → Optional[TradingSignal].
                       Returns None to reject.
        """
        self._risk_filters.append(filter_fn)

    def set_order_generator(self, generator: Callable) -> None:
        """Set the order generator function.

        Args:
            generator: Callable(signal, portfolio, cash, ctx) → List[Dict].
        """
        self._order_generator = generator

    # ── event handling ─────────────────────────────────────────────────────

    async def handle_event(self, event: BacktestEvent) -> None:
        """Handle a backtest event — main entry point from event engine."""
        # Store or update context based on event type
        if event.event_type == "position":
            self._current_positions = event.data.get("positions", {})

    async def on_market_data(self, market_data: Dict[str, Any]) -> List[TradingSignal]:
        """Process new market data and generate signals.

        Args:
            market_data: Bar/tick data from market replay.

        Returns:
            List of generated trading signals.
        """
        signals: List[TradingSignal] = []

        # Run through signal generators
        for generator in self._signal_generators:
            try:
                generated = generator(market_data, self._ctx)
                if generated:
                    signals.extend(generated)
            except Exception:
                logger.exception("Signal generator error")

        # Apply risk filters
        filtered_signals = []
        for signal in signals:
            accepted = True
            for risk_filter in self._risk_filters:
                try:
                    result = risk_filter(signal, self._current_positions, self._ctx)
                    if result is None:
                        accepted = False
                        logger.debug("Signal filtered: %s (%s)", signal.symbol, signal.signal_type.value)
                        break
                except Exception:
                    logger.exception("Risk filter error")
            if accepted:
                filtered_signals.append(signal)

        self._signals = filtered_signals
        return filtered_signals

    async def generate_orders(
        self,
        signal: Dict[str, Any],
        portfolio: Dict[str, Dict[str, Any]],
        cash: float,
    ) -> List[Dict[str, Any]]:
        """Convert signals to executable orders.

        Args:
            signal: Signal data dictionary.
            portfolio: Current portfolio positions.
            cash: Available cash.

        Returns:
            List of order dictionaries.
        """
        if self._order_generator:
            return self._order_generator(signal, portfolio, cash, self._ctx)

        # Default order generation: simple market orders based on signal
        orders = []
        symbol = signal.get("symbol", "")
        signal_type = signal.get("signal_type", "hold")
        strength = signal.get("strength", 0.0)
        target_weight = signal.get("target_weight")

        if self._order_mode == OrderGenerationMode.TARGET_WEIGHT and target_weight is not None:
            # Rebalance to target weight
            target_value = cash * target_weight
            current = portfolio.get(symbol, {"quantity": 0, "market_value": 0})
            current_mv = current.get("market_value", 0)
            if abs(target_value - current_mv) > 0.01 * cash:  # 1% threshold
                orders.append({
                    "order_id": str(uuid4()),
                    "symbol": symbol,
                    "side": "buy" if target_value > current_mv else "sell",
                    "order_type": "market",
                    "target_value": target_value,
                    "current_value": current_mv,
                    "market_data": signal.get("market_data", {}),
                })

        elif self._order_mode == OrderGenerationMode.SIGNAL_BASED:
            order = self._signal_to_order(symbol, signal_type, strength, signal.get("market_data", {}))
            if order:
                orders.append(order)

        return orders

    # ── signal helpers ─────────────────────────────────────────────────────

    def _signal_to_order(
        self,
        symbol: str,
        signal_type: str,
        strength: float,
        market_data: Dict[str, Any],
    ) -> Optional[Dict[str, Any]]:
        """Convert a raw signal to an order dictionary."""
        if signal_type in ("hold", "close"):
            return None

        side = signal_type
        if side in ("cover",):
            side = "buy"
        elif side in ("short",):
            side = "sell"

        return {
            "order_id": str(uuid4()),
            "symbol": symbol,
            "side": side,
            "order_type": "market",
            "strength": strength,
            "market_data": market_data,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }

    # ── query ──────────────────────────────────────────────────────────────

    def get_signals(self) -> List[TradingSignal]:
        """Get the latest generated signals."""
        return self._signals

    def get_current_positions(self) -> Dict[str, Dict[str, Any]]:
        """Get current portfolio positions."""
        return self._current_positions

    def get_stats(self) -> Dict[str, Any]:
        """Return strategy runner statistics."""
        return {
            "order_mode": self._order_mode.value,
            "signal_generators": len(self._signal_generators),
            "risk_filters": len(self._risk_filters),
            "active_signals": len(self._signals),
            "position_count": len(self._current_positions),
            "strategy": getattr(self._strategy, "__class__.__name__", None) if self._strategy else None,
        }
