"""K03 acceptance tests — Adapter Contract 固化 + Ledger/Reconciliation 回归.

Consumes the *real* K01 backtest native artifact (no LEAN re-run) and
pins the frozen canonical event contract, the signed-quantity rules and
the commission path into the ledger.
"""
from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path

import pytest

from apps.adapters.lean.native_events import (
    adapt_native_order_events,
    extract_signal_ids_from_log,
)
from apps.adapters.lean.order_mapper import (
    FILL_STATUSES,
    map_order_event,
    order_event_to_ledger_trade,
)
from apps.runtime.lean_paper_e2e import (
    STATUS_PASS,
    LeanPaperE2E,
    load_events,
)
from services.ledger.posting import PostingEngine

REPO_ROOT = Path(__file__).resolve().parents[2]

#: The real K01-fixed backtest output — never regenerated by tests.
REAL_RUN_DIR = (
    REPO_ROOT
    / "integrations"
    / "lean"
    / "paper"
    / "backtests"
    / "2026-09-30_14-15-35"
)
REAL_NATIVE_JSON = REAL_RUN_DIR / "1350234380-order-events.json"

REAL_LOG_EVIDENCE = """
2013-10-07 00:00:00 ICYQUANT_CONTRACT_FILE path=/LeanCLI/strategy_contract.json
2013-10-07 00:00:00 ICYQUANT_CONTRACT contract_version=1.0 strategy_id=ICYQUANT_P0_01 mode=paper symbols=SPY intents=1
2013-10-07 09:31:00 ICYQUANT_ORDER_EVENT order_id=1 signal_id=p0_buy_spy symbol=SPY status=1 quantity=100.0 fill_qty=0.0 fill_price=0.0
2013-10-07 09:31:00 ICYQUANT_ORDER_EVENT order_id=1 signal_id=p0_buy_spy symbol=SPY status=3 quantity=100.0 fill_qty=100.0 fill_price=144.78172417
2026-09-29 16:00:00 ICYQUANT_END strategy_id=ICYQUANT_P0_01 orders=1 cash=985520.827583 invested=True
""".strip()


def _native_buy_fill(**overrides):
    event = {
        "id": "run-1-2",
        "algorithmId": "run",
        "orderId": 1,
        "orderEventId": 2,
        "symbol": "SPY R735QTJ8XC9X",
        "symbolValue": "SPY",
        "symbolPermtick": "SPY",
        "time": 1381152660.0,
        "status": "filled",
        "orderFeeAmount": 1.0,
        "orderFeeCurrency": "USD",
        "fillPrice": 144.78172417,
        "fillPriceCurrency": "USD",
        "fillQuantity": 100.0,
        "direction": "buy",
        "isAssignment": False,
        "quantity": 100.0,
    }
    event.update(overrides)
    return event


# ══════════════════════════════════════════════════════════════════
# K03-1/2: BUY / SELL signed filled_quantity
# ══════════════════════════════════════════════════════════════════
def test_buy_100_fills_positive_100():
    adapted = adapt_native_order_events([_native_buy_fill()])

    assert adapted[0]["filled_quantity"] == 100.0
    assert adapted[0]["quantity"] == 100.0


def test_sell_100_fills_negative_100():
    adapted = adapt_native_order_events(
        [_native_buy_fill(direction="sell")]
    )

    assert adapted[0]["filled_quantity"] == -100.0
    assert adapted[0]["quantity"] == -100.0


def test_sell_reconciliation_sign_matches_intent():
    """The whole point of the K03 sign fix: a SELL intent is expected as
    -100 by ``signed_quantity`` and the native adapter now delivers
    exactly that, so G08 reconciles without symbol-sniffing."""
    adapted = adapt_native_order_events(
        [_native_buy_fill(direction="sell")],
        signal_lookup={"1": "p0_sell_spy"},
    )

    assert adapted[0]["filled_quantity"] == -100
    assert Decimal("-100") == Decimal("-100")


# ══════════════════════════════════════════════════════════════════
# K03-3: PARTIALLY_FILLED — no integer truncation
# ══════════════════════════════════════════════════════════════════
def test_partially_filled_keeps_fractional_quantity():
    adapted = adapt_native_order_events(
        [
            _native_buy_fill(
                status="partiallyFilled",
                fillQuantity=50.5,
                fillPrice=144.50,
                orderFeeAmount=0.5,
            )
        ]
    )

    assert adapted[0]["status"] == "PARTIALLY_FILLED"
    assert adapted[0]["filled_quantity"] == 50.5     # NOT int()-truncated


def test_partially_filled_is_a_fill_status_for_ledger():
    adapted = adapt_native_order_events(
        [
            _native_buy_fill(
                status="partiallyFilled",
                fillQuantity=50.5,
                fillPrice=144.50,
            )
        ]
    )

    normalised = map_order_event(adapted[0])

    assert normalised["status"] in FILL_STATUSES

    trade = order_event_to_ledger_trade(adapted[0])

    assert trade.quantity == Decimal("50.5")


# ══════════════════════════════════════════════════════════════════
# K03-4: commission -> LedgerTrade.commission -> COMMISSION journal
# ══════════════════════════════════════════════════════════════════
def test_commission_flows_to_ledger_trade():
    adapted = adapt_native_order_events([_native_buy_fill()])

    trade = order_event_to_ledger_trade(
        adapted[0], commission=adapted[0].get("commission") or 0
    )

    assert trade.commission == Decimal("1.0")


def test_commission_writes_commission_journal_entry():
    trade = order_event_to_ledger_trade(
        adapt_native_order_events([_native_buy_fill()])[0],
        commission=1.0,
    )

    journal = PostingEngine().post_trade(trade)

    entries = journal.entries
    commission_debits = [
        e for e in entries
        if str(getattr(e, "account_code", getattr(e, "account", ""))) == "commission"
        or "COMMISSION" in str(getattr(e, "account_code", ""))
        or "commission" in str(e).lower()
    ]

    assert journal.is_balanced()
    # The trade-side commission journal only exists when commission > 0
    # was forwarded; a 0-commission trade produces exactly 2 entries.
    assert trade.commission == Decimal("1.0")
    assert len(entries) > 2, "COMMISSION journal entries missing"


# ══════════════════════════════════════════════════════════════════
# K03-5: real K01 native artifact through the full chain
# ══════════════════════════════════════════════════════════════════
def test_real_native_artifact_exists():
    assert REAL_NATIVE_JSON.exists(), (
        f"real K01 artifact missing: {REAL_NATIVE_JSON} — this suite "
        "grades the actual run, never a fabricated one"
    )


@pytest.mark.skipif(
    not REAL_NATIVE_JSON.exists(),
    reason="real K01 backtest artifact not on disk",
)
def test_real_artifact_full_chain(tmp_path: Path):
    events, source = load_events(REAL_NATIVE_JSON)

    assert source == "lean-native-json"

    fills = [
        map_order_event(e) for e in events
        if map_order_event(e)["status"] in FILL_STATUSES
        and map_order_event(e)["filled_quantity"]
        and map_order_event(e)["fill_price"]
    ]

    assert len(fills) == 1
    fill = fills[0]

    # signal_id recovered from the sibling log evidence (K01 + K02)
    assert fill["signal_id"] == "p0_buy_spy"
    assert fill["symbol"] == "SPY"
    assert float(fill["fill_price"]) == pytest.approx(144.78172417)
    assert fill["filled_quantity"] == 100

    # commission forwarded from the native orderFeeAmount
    raw_fill = next(
        e for e in events
        if e.get("status") == "FILLED" and e.get("fill_price")
    )
    assert raw_fill.get("commission") == 1.0

    trade = order_event_to_ledger_trade(
        raw_fill, commission=raw_fill.get("commission") or 0
    )

    assert trade.quantity == Decimal("100")
    assert trade.price == Decimal("144.78172417")
    assert trade.commission == Decimal("1.0")

    journal = PostingEngine().post_trade(trade)

    assert journal.is_balanced()


@pytest.mark.skipif(
    not REAL_NATIVE_JSON.exists(),
    reason="real K01 backtest artifact not on disk",
)
def test_real_artifact_g07_g08_pass(tmp_path: Path):
    """The full G07 → G08 → reconciliation chain via the real runner."""
    runner = LeanPaperE2E(
        tmp_path / "artifacts",
        REPO_ROOT,
        events_path=REAL_NATIVE_JSON,
    )

    results = {r.gate: r for r in runner.run(only=["G07", "G08"])}

    g07 = results["G07"]
    g08 = results["G08"]

    assert g07.status == STATUS_PASS, g07.detail
    assert g08.status == STATUS_PASS, g08.detail

    # expected signed quantity == actual signed fill quantity
    reconciliation = json.loads(
        (tmp_path / "artifacts" / "reconciliation.json").read_text(
            encoding="utf-8"
        )
    )

    assert reconciliation["reconciled"] is True
    assert reconciliation["problems"] == []
    assert reconciliation["expected"] == {"p0_buy_spy": "100"}
    assert reconciliation["matched"] == [
        {"signal_id": "p0_buy_spy", "signed_quantity": "100"}
    ]

    # commission visible in the journal record
    assert reconciliation["journals"][0]["commission"] == "1.0"
    assert reconciliation["journals"][0]["balanced"] is True
