class EventType:
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    TRADE_EXECUTED = "TRADE_EXECUTED"
    POSITION_UPDATED = "POSITION_UPDATED"
    MARKET_DATA_UPDATED = "MARKET_DATA_UPDATED"