"""
Governance Intervention — unified intervention execution engine.

Part 1.5: executes intervention plans generated by the control plane,
with step-by-step execution, verification, and audit recording.
"""

from __future__ import annotations

import time
import uuid
from typing import Any, Dict, List, Optional

from .intervention_plan import InterventionPlan, InterventionStep
from .intervention_result import InterventionResult
from .control_decision import ControlDecision


class GovernanceIntervention:
    """Executes governance intervention plans and records results."""

    def __init__(
        self,
        freeze_controller: Any = None,
        exposure_controller: Any = None,
        revoke_controller: Any = None,
        escalation_controller: Any = None,
        audit_engine: Any = None,
    ):
        self._freeze_controller = freeze_controller
        self._exposure_controller = exposure_controller
        self._revoke_controller = revoke_controller
        self._escalation_controller = escalation_controller
        self._audit_engine = audit_engine

        self._results: List[InterventionResult] = []
        self._max_results = 10000

    def execute(self, plan: InterventionPlan) -> InterventionResult:
        """Execute an intervention plan step by step.

        Each step is executed in order. Required steps that fail cause
        the intervention to fail. Non-required steps are attempted but
        failure is tolerated.
        """
        result = InterventionResult(
            result_id=plan.plan_id,
            plan_id=plan.plan_id,
            plan_description=plan.description,
            correlation_id=plan.correlation_id,
        )

        step_results: List[Dict[str, Any]] = []
        all_success = True
        errors: List[str] = []

        plan.state = "EXECUTING"

        for step in sorted(plan.steps, key=lambda s: s.order):
            try:
                step_result = self._execute_step(step, plan.correlation_id)
                step.mark_executed(step_result)
                step_results.append({
                    "step_id": step.step_id,
                    "order": step.order,
                    "type": step.step_type.name,
                    "executed": True,
                    "result": step_result,
                })

                if step_result.get("status") == "FAILED" and step.required:
                    all_success = False
                    errors.append(f"Step {step.order}: {step.description} failed - {step_result.get('error', '')}")

            except Exception as e:
                step.mark_failed(str(e))
                step_results.append({
                    "step_id": step.step_id,
                    "order": step.order,
                    "type": step.step_type.name,
                    "executed": True,
                    "error": str(e),
                })
                if step.required:
                    all_success = False
                    errors.append(f"Step {step.order}: {step.description} - {e}")

        # Complete
        result.complete(all_success, step_results)
        result.errors = errors

        if all_success:
            plan.complete()
        else:
            plan.fail()

        self._results.append(result)
        if len(self._results) > self._max_results:
            self._results = self._results[-self._max_results:]

        # Audit
        self._audit_execution(result)

        return result

    def _execute_step(
        self, step: InterventionStep, correlation_id: str
    ) -> Dict[str, Any]:
        """Execute a single intervention step."""
        step_type = step.step_type

        if step_type.name == "FREEZE":
            if self._freeze_controller:
                scope = step.parameters.get("scope", "GLOBAL")
                return self._freeze_controller.freeze(
                    scope=scope,
                    target=step.target,
                    reason=step.description,
                    correlation_id=correlation_id,
                )
            return {"status": "NO_OP", "reason": "FreezeController not available."}

        elif step_type.name == "CANCEL":
            if self._freeze_controller:
                return self._freeze_controller.cancel_pending(
                    reason=step.description,
                    correlation_id=correlation_id,
                )
            return {"status": "NO_OP", "reason": "FreezeController not available."}

        elif step_type.name == "REDUCE":
            if self._exposure_controller:
                target_pct = step.parameters.get("target_exposure", 0.10)
                return self._exposure_controller.reduce_exposure(
                    target_exposure=target_pct,
                    reason=step.description,
                    correlation_id=correlation_id,
                )
            return {"status": "NO_OP", "reason": "ExposureController not available."}

        elif step_type.name == "REVOKE":
            if self._revoke_controller:
                return self._revoke_controller.revoke(
                    target=step.target,
                    reason=step.description,
                    correlation_id=correlation_id,
                )
            return {"status": "NO_OP", "reason": "RevokeController not available."}

        elif step_type.name == "ESCALATE":
            if self._escalation_controller:
                return self._escalation_controller.escalate(
                    reason=step.description,
                    correlation_id=correlation_id,
                    trigger_type=step.parameters.get("trigger_type", ""),
                )
            return {"status": "NO_OP", "reason": "EscalationController not available."}

        elif step_type.name == "NOTIFY":
            return {"status": "NOTIFIED", "message": step.description}

        elif step_type.name == "PAUSE":
            return {"status": "PAUSED", "target": step.target}

        elif step_type.name == "VERIFY":
            return {"status": "VERIFIED", "target": step.target}

        elif step_type.name == "RECOVER":
            return {"status": "RECOVERED", "target": step.target}

        return {"status": "UNKNOWN", "step_type": step_type.name}

    def _audit_execution(self, result: InterventionResult) -> None:
        """Record audit for intervention execution."""
        if not self._audit_engine:
            result.audit_recorded = False
            return

        try:
            self._audit_engine.record_event(
                event_type=None,
                entity_type="INTERVENTION",
                entity_id=result.result_id,
                actor=None,
                action=None,
                outcome=None,
                reason=result.plan_description,
                correlation_id=result.correlation_id,
            )
            result.audit_recorded = True
        except Exception:
            result.audit_recorded = False

    def get_results(self, limit: int = 100) -> List[Dict[str, Any]]:
        return [r.to_dict() for r in reversed(self._results[-limit:])]

    def get_metrics(self) -> Dict[str, Any]:
        successes = sum(1 for r in self._results if r.success)
        failures = sum(1 for r in self._results if not r.success)
        return {
            "total_interventions": len(self._results),
            "successes": successes,
            "failures": failures,
            "success_rate": successes / max(len(self._results), 1),
        }
