"""
Intervention Plan — structured governance intervention plans.

Part 1.5: each governance signal can generate a structured intervention
plan with ordered steps, each verifiable and auditable.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional


class InterventionStepType(Enum):
    """Types of intervention steps."""

    FREEZE = auto()
    CANCEL = auto()
    REDUCE = auto()
    REVOKE = auto()
    PAUSE = auto()
    NOTIFY = auto()
    ESCALATE = auto()
    VERIFY = auto()
    RECOVER = auto()


@dataclass
class InterventionStep:
    """A single step in an intervention plan."""

    step_id: str = field(default_factory=lambda: f"STEP-{uuid.uuid4().hex[:8].upper()}")
    order: int = 0
    step_type: InterventionStepType = InterventionStepType.NOTIFY
    description: str = ""
    target: str = ""            # What the step targets
    parameters: Dict[str, Any] = field(default_factory=dict)
    timeout_seconds: float = 60.0
    retry_count: int = 0
    max_retries: int = 3
    required: bool = True       # Must succeed for plan to complete
    executed: bool = False
    executed_at: float = 0.0
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    def mark_executed(self, result: Dict[str, Any]) -> None:
        self.executed = True
        self.executed_at = time.time()
        self.result = result

    def mark_failed(self, error: str) -> None:
        self.executed = True
        self.executed_at = time.time()
        self.error = error

    def to_dict(self) -> Dict[str, Any]:
        return {
            "step_id": self.step_id,
            "order": self.order,
            "step_type": self.step_type.name,
            "description": self.description,
            "target": self.target,
            "required": self.required,
            "executed": self.executed,
            "executed_at": self.executed_at,
            "result": self.result,
            "error": self.error,
        }


@dataclass
class InterventionPlan:
    """A complete governance intervention plan.

    Generated by the control plane when triggers fire. Contains ordered
    steps with verification requirements and audit trail.
    """

    plan_id: str = field(default_factory=lambda: f"IPLN-{uuid.uuid4().hex[:12].upper()}")
    trigger: str = ""           # What triggered this intervention
    description: str = ""
    severity: str = "LOW"
    steps: List[InterventionStep] = field(default_factory=list)
    correlation_id: str = ""
    state: str = "DRAFT"        # DRAFT → EXECUTING → COMPLETED / FAILED
    created_at: float = field(default_factory=time.time)
    completed_at: float = 0.0
    actor: str = "control-plane"
    metadata: Dict[str, Any] = field(default_factory=dict)

    def add_step(
        self,
        step_type: InterventionStepType,
        description: str,
        target: str = "",
        required: bool = True,
        **params,
    ) -> InterventionStep:
        step = InterventionStep(
            order=len(self.steps),
            step_type=step_type,
            description=description,
            target=target,
            parameters=params,
            required=required,
        )
        self.steps.append(step)
        return step

    def get_next_step(self) -> Optional[InterventionStep]:
        """Get the next unexecuted step."""
        for step in sorted(self.steps, key=lambda s: s.order):
            if not step.executed:
                return step
        return None

    def is_complete(self) -> bool:
        return all(s.executed and not s.error for s in self.steps if s.required)

    def is_failed(self) -> bool:
        return any(s.error and s.required for s in self.steps)

    def complete(self) -> None:
        self.state = "COMPLETED"
        self.completed_at = time.time()

    def fail(self) -> None:
        self.state = "FAILED"
        self.completed_at = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "trigger": self.trigger,
            "description": self.description,
            "severity": self.severity,
            "state": self.state,
            "steps": [s.to_dict() for s in sorted(self.steps, key=lambda x: x.order)],
            "correlation_id": self.correlation_id,
            "created_at": self.created_at,
            "completed_at": self.completed_at,
        }

    # ── Factory: Pre-built intervention plans ──

    @classmethod
    def drawdown_restrict_plan(
        cls,
        drawdown: float,
        correlation_id: str = "",
    ) -> "InterventionPlan":
        """Create an intervention plan for drawdown → RESTRICTED."""
        plan = cls(
            trigger=f"Drawdown {drawdown:.1%}",
            description="Restrict due to elevated drawdown.",
            severity="MEDIUM",
            correlation_id=correlation_id,
        )
        plan.add_step(InterventionStepType.FREEZE, "Freeze new allocation")
        plan.add_step(InterventionStepType.CANCEL, "Cancel pending oversized orders")
        plan.add_step(InterventionStepType.REDUCE, "Reduce leverage to allowed limit")
        plan.add_step(InterventionStepType.NOTIFY, "Notify Risk Manager")
        plan.add_step(InterventionStepType.VERIFY, "Verify risk metrics within limits")
        return plan

    @classmethod
    def drawdown_freeze_plan(
        cls,
        drawdown: float,
        correlation_id: str = "",
    ) -> "InterventionPlan":
        """Create an intervention plan for drawdown → FROZEN."""
        plan = cls(
            trigger=f"Drawdown {drawdown:.1%}",
            description="Freeze new risk due to severe drawdown.",
            severity="HIGH",
            correlation_id=correlation_id,
        )
        plan.add_step(InterventionStepType.FREEZE, "Global new-risk freeze")
        plan.add_step(InterventionStepType.CANCEL, "Cancel all pending orders")
        plan.add_step(InterventionStepType.REDUCE, "Reduce exposure to 10%")
        plan.add_step(InterventionStepType.ESCALATE, "Escalate to Risk Manager")
        plan.add_step(InterventionStepType.VERIFY, "Verify freeze in effect")
        return plan

    @classmethod
    def emergency_plan(
        cls,
        trigger: str,
        correlation_id: str = "",
    ) -> "InterventionPlan":
        """Create an intervention plan for EMERGENCY."""
        plan = cls(
            trigger=trigger,
            description="Emergency governance action.",
            severity="CRITICAL",
            correlation_id=correlation_id,
        )
        plan.add_step(InterventionStepType.FREEZE, "Global freeze on all new risk")
        plan.add_step(InterventionStepType.CANCEL, "Cancel all pending orders")
        plan.add_step(InterventionStepType.REVOKE, "Revoke compromised authorities")
        plan.add_step(InterventionStepType.ESCALATE, "Escalate to Investment Committee")
        plan.add_step(InterventionStepType.VERIFY, "Verify emergency state")
        return plan
