class OrderStatus:

    CREATED = "CREATED"

    SUBMITTED = "SUBMITTED"

    ACCEPTED = "ACCEPTED"

    PARTIAL_FILLED = "PARTIAL_FILLED"

    FILLED = "FILLED"

    CANCELLED = "CANCELLED"

    REJECTED = "REJECTED"