"""Strategy Runtime Adapter — trading strategy pipeline orchestration.

Bridges trading strategies with the workflow engine, enabling:

    Trading Strategy → Signal → Workflow → Risk → Execution

Makes strategy execution fully workflow-driven, providing audit trails,
retry capabilities, and distributed execution for strategy pipelines.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


class StrategyStatus(str, Enum):
    CREATED = "CREATED"
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"
    ERROR = "ERROR"


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy."""

    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_id: str = ""
    symbol: str = ""
    direction: str = ""  # LONG / SHORT
    quantity: float = 0.0
    confidence: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "direction": self.direction,
            "quantity": self.quantity,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class StrategyConfig:
    """Configuration for a trading strategy running on the workflow engine."""

    strategy_id: str
    name: str = ""
    workflow_id: str = ""
    symbols: List[str] = field(default_factory=list)
    parameters: Dict[str, Any] = field(default_factory=dict)
    enabled: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)


class StrategyRuntimeAdapter:
    """Bridges trading strategies with the workflow engine.

    Usage::

        adapter = StrategyRuntimeAdapter()
        await adapter.start()
        signal = await adapter.process_signal(StrategySignal(strategy_id="ma_cross", symbol="AAPL"))
    """

    def __init__(self) -> None:
        self._lock = __import__("threading").RLock()
        self._started = False
        self._strategies: Dict[str, StrategyConfig] = {}
        self._signals: Dict[str, StrategySignal] = {}
        self._on_signal_callbacks: List[Callable] = []

    async def start(self) -> None:
        self._started = True
        logger.info("StrategyRuntimeAdapter: started")

    async def stop(self) -> None:
        self._started = False
        logger.info("StrategyRuntimeAdapter: stopped")

    async def register_strategy(self, config: StrategyConfig) -> None:
        with self._lock:
            self._strategies[config.strategy_id] = config
        logger.info("StrategyRuntimeAdapter: registered strategy %s → workflow %s", config.strategy_id, config.workflow_id)

    async def deregister_strategy(self, strategy_id: str) -> bool:
        with self._lock:
            return self._strategies.pop(strategy_id, None) is not None

    async def process_signal(self, signal: StrategySignal) -> str:
        """Process a trading signal through the workflow engine.

        Returns the workflow execution_id.
        """
        with self._lock:
            self._signals[signal.signal_id] = signal

        logger.info("StrategyRuntimeAdapter: processing signal %s (%s %s %s x%.0f, confidence=%.2f)",
                     signal.signal_id, signal.strategy_id, signal.symbol, signal.direction,
                     signal.quantity, signal.confidence)

        for cb in self._on_signal_callbacks:
            try:
                cb(signal)
            except Exception:
                logger.exception("StrategyRuntimeAdapter: signal callback error")

        return signal.signal_id  # Returns signal_id as workflow trigger reference

    async def get_signal(self, signal_id: str) -> Optional[StrategySignal]:
        with self._lock:
            return self._signals.get(signal_id)

    async def list_signals(
        self,
        *,
        strategy_id: Optional[str] = None,
        symbol: Optional[str] = None,
        limit: int = 100,
    ) -> List[StrategySignal]:
        with self._lock:
            results = list(self._signals.values())
            if strategy_id:
                results = [s for s in results if s.strategy_id == strategy_id]
            if symbol:
                results = [s for s in results if s.symbol == symbol]
            return sorted(results, key=lambda s: s.timestamp, reverse=True)[:limit]

    def on_signal(self, callback: Callable) -> None:
        self._on_signal_callbacks.append(callback)

    def health_report(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "strategies": len(self._strategies),
                "signals": len(self._signals),
                "strategies_list": list(self._strategies.keys()),
            }
