"""ICYQuant Distributed Scheduler — unified scheduling runtime for the ICYQuant platform.

The scheduler is the platform layer responsible for *when*, *where*, and *who*:

* When to execute — trigger evaluation (cron, interval, calendar, event)
* Where to execute — resource allocation and worker selection
* Who executes — job dispatch to specific workers/nodes

The Workflow Engine (``services/workflow``) handles *what* and *how*.
"""

from .scheduler_engine import SchedulerEngine, EngineState
from .scheduler_manager import SchedulerManager, ManagerState
from .scheduler_runtime import SchedulerRuntime
from .scheduler_context import SchedulerContext, create_scheduler_context
from .scheduler_config import SchedulerConfig
from .scheduler_registry import SchedulerRegistry
from .scheduler_factory import SchedulerFactory
from .scheduler_repository import SchedulerRepository
from .scheduler_loader import SchedulerLoader
from .scheduler_validator import validate_schedule, validate_schedule_config, ValidationError
from .scheduler_snapshot import SchedulerSnapshot
from .scheduler_serializer import SchedulerSerializer
from .scheduler_service import SchedulerService
from .api import SchedulerAPI
from .metrics import SchedulerMetrics
from .telemetry import SchedulerTelemetry, TelemetrySpan
from .diagnostics import SchedulerDiagnostics, DiagnosticsReport
from .health import SchedulerHealth

from .trigger import (
    TriggerEngine,
    TriggerEngineState,
    TriggerManager as TriggerMgr,
    TriggerManagerState,
    TriggerContext,
    create_trigger_context,
    TriggerRegistry,
    TriggerFactory,
    TriggerValidator,
    TriggerValidationError,
    TriggerDispatcher,
    DispatchResult,
    CronTrigger,
    CronParser,
    CronExpression,
    CronField,
    IntervalTrigger,
    CalendarTrigger,
    TradingCalendar,
    Market,
    SessionCalendar,
    TradingSession,
    HolidayCalendar,
    Holiday,
    MarketCalendar,
    EventTrigger,
    ManualTrigger,
    WebhookTrigger,
    DependencyTrigger,
    DependencyPolicy,
    PriorityQueue,
    QueueItem,
    TriggerScheduler,
    MisfireHandler,
    MisfirePolicy,
    RetryPolicy,
    BackoffStrategy,
    TriggerSimulator,
    TriggerMetrics,
    TriggerTelemetry,
    TriggerDiagnostics,
    TriggerHealth,
)

from .models import (
    ScheduleDefinition,
    ScheduleType,
    ScheduleStatus,
    ScheduleConfig,
    TriggerDefinition,
    TriggerType,
    TriggerState,
    JobDefinition,
    JobState,
    JobPriority,
    JobConfig,
    ExecutionRecord,
    ExecutionState,
    ExecutionResult,
    ResourceSpec,
    ResourceRequirement,
    ResourcePool,
    CalendarEntry,
    CalendarType,
    CalendarRule,
    ScheduleMetadata,
    JobMetadata,
    ExecutionMetadata,
)

from .resource import (
    ResourceManager,
    ResourceManagerState,
    ResourcePool as SchedulerResourcePool,
    ResourceTracker,
    ResourceMonitor,
    ResourceEstimator,
    EstimateResult,
    ResourcePredictor,
    PredictionResult,
    ResourceQuota,
    QuotaLimit,
    ResourceReservation,
    ReservationStatus,
    ResourceAllocator,
    AllocationResult,
    ResourceReclaimer,
    NodeInventory,
    NodeRecord,
    NodeScoringEngine,
    NodeScore,
    NodeSelector,
    SelectionStrategy,
    PlacementPlanner,
    PlacementPlan,
    AffinityRule,
    AffinityType,
    AntiAffinityRule,
    TopologyManager,
    TopologyDomain,
    SchedulerPolicy,
    PolicyType,
    FairShareScheduler,
    FairShareResult,
    PriorityScheduler,
    PreemptionScheduler,
    PreemptionResult,
    BinPackingOptimizer,
    PackingResult,
    AutoScaler,
    ScalingResult,
    CapacityPlanner,
    CapacityPlan,
    CostOptimizer,
    CostResult,
    GPUScheduler,
    IOScheduler,
    ResourceMetrics,
    ResourceTelemetry,
    ResourceDiagnostics,
    ResourceHealth,
)

from .cluster import (
    SchedulerClusterManager,
    ClusterState,
    ClusterRuntime,
    ClusterRuntimePhase,
    ClusterCoordinator,
    CoordinatorRole,
    SchedulerNode,
    NodeRole,
    NodeRegistry as ClusterNodeRegistry,
    NodeStatus as ClusterNodeStatus,
    HeartbeatManager as ClusterHeartbeatManager,
    HeartbeatStatus as ClusterHeartbeatStatus,
    ClusterHealthMonitor,
    NodeHealthStatus,
    LeaderElection,
    ElectionResult,
    ElectionProvider,
    ConsensusLayer,
    ConsensusResult,
    LeaseManager,
    LeaseStatus,
    DistributedLock,
    LockType,
    LockAcquisition,
    DistributedQueue,
    QueueType,
    QueueEntry as ClusterQueueEntry,
    QueuePartitioner,
    PartitionStrategy,
    QueueReplication,
    ReplicationMode,
    QueueRebalancer,
    RebalancePlan,
    SchedulerReplication,
    ReplicationState,
    StateSync,
    SyncMode,
    JobReplication,
    JobReplica,
    ClusterDispatcher,
    DispatchTarget,
    FailoverManager,
    FailoverState,
    RecoveryCoordinator,
    RecoveryPlan,
    DisasterRecovery,
    DRSite,
    MultiRegionManager,
    RegionRole,
    ClusterTopologyManager,
    ClusterDomain,
    ClusterMetrics,
    ClusterTelemetry,
    ClusterDiagnostics,
    ClusterHealth,
)

from .integration import (
    SchedulerIntegrationManager,
    IntegrationState,
    PlatformRuntime,
    PlatformRuntimePhase,
    SchedulerGateway,
    GatewayMode,
    WorkflowAdapter,
    WorkflowAdapterState,
    WorkflowBridge,
    BridgeState,
    EventBusAdapter,
    EventBusAdapterState,
    ServiceMeshAdapter,
    MeshMode,
    ConfigurationAdapter,
    ConfigSource,
    FeatureFlagAdapter,
    FlagEvaluation,
    DiscoveryAdapter,
    ServiceInstance,
    SecretsAdapter,
    SecretProvider,
    StrategyRuntimeAdapter,
    StrategyAdapterState,
    AIRuntimeAdapter,
    AIAdapterState,
    ResearchRuntimeAdapter,
    ResearchAdapterState,
    MarketDataAdapter,
    MarketEventType,
    OrderAdapter,
    OrderAdapterState,
    RiskAdapter,
    RiskAdapterState,
    ExecutionAdapter,
    ExecutionAdapterState,
    SettlementAdapter,
    SettlementAdapterState,
    LedgerAdapter,
    LedgerAdapterState,
    NotificationAdapter,
    NotificationChannel,
    WebhookAdapter,
    WebhookDelivery,
    DashboardAPI,
    DashboardEndpoint,
    SchedulerSDK,
    SDKClient,
    SchedulerCLI,
    CLICommand,
    IntegrationMetrics,
    IntegrationTelemetry,
    TelemetryAdapter,
    TelemetryProtocol,
    TracingAdapter,
    TraceContext,
    MetricsAdapter,
    MetricsSink,
    IntegrationDiagnostics,
    IntegrationHealth,
)

from .runtime import (
    RuntimeManager,
    RuntimeState,
    RuntimeStateManager,
    RuntimePhase,
    SchedulerEventBus,
    SchedulerEventType,
    SchedulerEvent,
    RuntimeMetricsCollector,
    RuntimeHealthChecker,
    RuntimeScheduler,
)

__all__ = [
    # Engine
    "SchedulerEngine",
    "EngineState",
    "SchedulerManager",
    "ManagerState",
    "SchedulerRuntime",
    # Context & Config
    "SchedulerContext",
    "create_scheduler_context",
    "SchedulerConfig",
    # Registry & Factory
    "SchedulerRegistry",
    "SchedulerFactory",
    # Repository & Loader
    "SchedulerRepository",
    "SchedulerLoader",
    # Validation
    "validate_schedule",
    "validate_schedule_config",
    "ValidationError",
    # Snapshot & Serializer
    "SchedulerSnapshot",
    "SchedulerSerializer",
    # Service & API
    "SchedulerService",
    "SchedulerAPI",
    # Observability
    "SchedulerMetrics",
    "SchedulerTelemetry",
    "TelemetrySpan",
    "SchedulerDiagnostics",
    "DiagnosticsReport",
    "SchedulerHealth",
    # Models
    "ScheduleDefinition",
    "ScheduleType",
    "ScheduleStatus",
    "ScheduleConfig",
    "TriggerDefinition",
    "TriggerType",
    "TriggerState",
    "JobDefinition",
    "JobState",
    "JobPriority",
    "JobConfig",
    "ExecutionRecord",
    "ExecutionState",
    "ExecutionResult",
    "ResourceSpec",
    "ResourceRequirement",
    "ResourcePool",
    "CalendarEntry",
    "CalendarType",
    "CalendarRule",
    "ScheduleMetadata",
    "JobMetadata",
    "ExecutionMetadata",
    # Runtime
    "RuntimeManager",
    "RuntimeState",
    "RuntimeStateManager",
    "RuntimePhase",
    "SchedulerEventBus",
    "SchedulerEventType",
    "SchedulerEvent",
    "RuntimeMetricsCollector",
    "RuntimeHealthChecker",
    "RuntimeScheduler",
    # Trigger Engine
    "TriggerEngine",
    "TriggerEngineState",
    "TriggerMgr",
    "TriggerManagerState",
    "TriggerContext",
    "create_trigger_context",
    "TriggerRegistry",
    "TriggerFactory",
    "TriggerValidator",
    "TriggerValidationError",
    "TriggerDispatcher",
    "DispatchResult",
    # Time Triggers
    "CronTrigger",
    "CronParser",
    "CronExpression",
    "CronField",
    "IntervalTrigger",
    # Calendar Triggers
    "CalendarTrigger",
    "TradingCalendar",
    "Market",
    "SessionCalendar",
    "TradingSession",
    "HolidayCalendar",
    "Holiday",
    "MarketCalendar",
    # Event Triggers
    "EventTrigger",
    "ManualTrigger",
    "WebhookTrigger",
    "DependencyTrigger",
    "DependencyPolicy",
    # Scheduling Infrastructure
    "PriorityQueue",
    "QueueItem",
    "TriggerScheduler",
    "MisfireHandler",
    "MisfirePolicy",
    "RetryPolicy",
    "BackoffStrategy",
    "TriggerSimulator",
    # Trigger Observability
    "TriggerMetrics",
    "TriggerTelemetry",
    "TriggerDiagnostics",
    "TriggerHealth",
    # Resource Scheduling
    "ResourceManager",
    "ResourceManagerState",
    "SchedulerResourcePool",
    "ResourceTracker",
    "ResourceMonitor",
    "ResourceEstimator",
    "EstimateResult",
    "ResourcePredictor",
    "PredictionResult",
    "ResourceQuota",
    "QuotaLimit",
    "ResourceReservation",
    "ReservationStatus",
    "ResourceAllocator",
    "AllocationResult",
    "ResourceReclaimer",
    # Node & Placement
    "NodeInventory",
    "NodeRecord",
    "NodeScoringEngine",
    "NodeScore",
    "NodeSelector",
    "SelectionStrategy",
    "PlacementPlanner",
    "PlacementPlan",
    # Affinity & Topology
    "AffinityRule",
    "AffinityType",
    "AntiAffinityRule",
    "TopologyManager",
    "TopologyDomain",
    # Scheduling Policies
    "SchedulerPolicy",
    "PolicyType",
    "FairShareScheduler",
    "FairShareResult",
    "PriorityScheduler",
    "PreemptionScheduler",
    "PreemptionResult",
    "BinPackingOptimizer",
    "PackingResult",
    # Elastic & Cost
    "AutoScaler",
    "ScalingResult",
    "CapacityPlanner",
    "CapacityPlan",
    "CostOptimizer",
    "CostResult",
    "GPUScheduler",
    "IOScheduler",
    # Resource Observability
    "ResourceMetrics",
    "ResourceTelemetry",
    "ResourceDiagnostics",
    "ResourceHealth",
    # High-Availability Cluster
    "SchedulerClusterManager",
    "ClusterState",
    "ClusterRuntime",
    "ClusterRuntimePhase",
    "ClusterCoordinator",
    "CoordinatorRole",
    "SchedulerNode",
    "NodeRole",
    "ClusterNodeRegistry",
    "ClusterNodeStatus",
    "ClusterHeartbeatManager",
    "ClusterHeartbeatStatus",
    "ClusterHealthMonitor",
    "NodeHealthStatus",
    "LeaderElection",
    "ElectionResult",
    "ElectionProvider",
    "ConsensusLayer",
    "ConsensusResult",
    "LeaseManager",
    "LeaseStatus",
    "DistributedLock",
    "LockType",
    "LockAcquisition",
    "DistributedQueue",
    "QueueType",
    "ClusterQueueEntry",
    "QueuePartitioner",
    "PartitionStrategy",
    "QueueReplication",
    "ReplicationMode",
    "QueueRebalancer",
    "RebalancePlan",
    "SchedulerReplication",
    "ReplicationState",
    "StateSync",
    "SyncMode",
    "JobReplication",
    "JobReplica",
    "ClusterDispatcher",
    "DispatchTarget",
    "FailoverManager",
    "FailoverState",
    "RecoveryCoordinator",
    "RecoveryPlan",
    "DisasterRecovery",
    "DRSite",
    "MultiRegionManager",
    "RegionRole",
    "ClusterTopologyManager",
    "ClusterDomain",
    "ClusterMetrics",
    "ClusterTelemetry",
    "ClusterDiagnostics",
    "ClusterHealth",
    # Platform Integration
    "SchedulerIntegrationManager",
    "IntegrationState",
    "PlatformRuntime",
    "PlatformRuntimePhase",
    "SchedulerGateway",
    "GatewayMode",
    # Workflow & Event
    "WorkflowAdapter",
    "WorkflowAdapterState",
    "WorkflowBridge",
    "BridgeState",
    "EventBusAdapter",
    "EventBusAdapterState",
    # Infrastructure
    "ServiceMeshAdapter",
    "MeshMode",
    "ConfigurationAdapter",
    "ConfigSource",
    "FeatureFlagAdapter",
    "FlagEvaluation",
    "DiscoveryAdapter",
    "ServiceInstance",
    "SecretsAdapter",
    "SecretProvider",
    # Business Domains
    "StrategyRuntimeAdapter",
    "StrategyAdapterState",
    "AIRuntimeAdapter",
    "AIAdapterState",
    "ResearchRuntimeAdapter",
    "ResearchAdapterState",
    "MarketDataAdapter",
    "MarketEventType",
    "OrderAdapter",
    "OrderAdapterState",
    "RiskAdapter",
    "RiskAdapterState",
    "ExecutionAdapter",
    "ExecutionAdapterState",
    "SettlementAdapter",
    "SettlementAdapterState",
    "LedgerAdapter",
    "LedgerAdapterState",
    # Notification & Webhook
    "NotificationAdapter",
    "NotificationChannel",
    "WebhookAdapter",
    "WebhookDelivery",
    # Dashboard, SDK, CLI
    "DashboardAPI",
    "DashboardEndpoint",
    "SchedulerSDK",
    "SDKClient",
    "SchedulerCLI",
    "CLICommand",
    # Observability
    "IntegrationMetrics",
    "IntegrationTelemetry",
    "TelemetryAdapter",
    "TelemetryProtocol",
    "TracingAdapter",
    "TraceContext",
    "MetricsAdapter",
    "MetricsSink",
    "IntegrationDiagnostics",
    "IntegrationHealth",
]
