"""Strategy Agent — specialized agent for strategy development, evaluation, and signal generation.

Pipeline:
    Strategy request / Coordinator assignment
        -> StrategyAgent.develop() (create/update strategy)
        -> StrategyAgent.evaluate() (assess performance)
        -> StrategyAgent.generate_signals() (produce trading signals)
        -> publish signals to blackboard / message bus
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from services.ai_agent.collaboration.message_bus import MessageBus, Message, MessageType

logger = logging.getLogger(__name__)


class StrategyStatus(str, Enum):
    """Status of a trading strategy."""
    DRAFT = "draft"
    BACKTESTED = "backtested"
    PAPER_TRADING = "paper_trading"
    LIVE = "live"
    PAUSED = "paused"
    ARCHIVED = "archived"


class SignalDirection(str, Enum):
    """Direction of a trading signal."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class Strategy:
    """A trading strategy definition.

    Attributes:
        strategy_id: Unique strategy identifier.
        name: Strategy name.
        description: Strategy description.
        status: Current strategy status.
        parameters: Strategy parameters.
        metrics: Performance metrics.
        created_at: Creation timestamp.
    """

    strategy_id: str = field(default_factory=lambda: uuid4().hex)
    name: str = ""
    description: str = ""
    status: StrategyStatus = StrategyStatus.DRAFT
    parameters: Dict[str, Any] = field(default_factory=dict)
    metrics: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class TradingSignal:
    """A trading signal generated by a strategy.

    Attributes:
        signal_id: Unique signal identifier.
        strategy_id: Source strategy ID.
        symbol: Trading symbol.
        direction: Signal direction.
        confidence: Signal confidence (0.0 - 1.0).
        target_price: Optional target price.
        reason: Human-readable reason.
        timestamp: Signal generation time.
    """

    signal_id: str = field(default_factory=lambda: uuid4().hex)
    strategy_id: str = ""
    symbol: str = ""
    direction: SignalDirection = SignalDirection.HOLD
    confidence: float = 0.5
    target_price: Optional[float] = None
    reason: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class StrategyAgent:
    """Specialized agent for strategy development, evaluation, and signals.

    Develops trading strategies, evaluates their performance, and generates
    trading signals based on strategy rules.

    Supports:
        - Strategy development and management
        - Strategy evaluation
        - Signal generation
        - Strategy lifecycle management (draft → live)
        - Signal publication

    Usage:
        agent = StrategyAgent(agent_id="strategy_1", message_bus=bus)
        await agent.initialize()
        strategy = await agent.develop("momentum_strategy", {...})
        signals = await agent.generate_signals(strategy.strategy_id)
    """

    def __init__(
        self,
        agent_id: str = "",
        message_bus: Optional[MessageBus] = None,
    ) -> None:
        """Initialize the Strategy Agent.

        Args:
            agent_id: Unique agent identifier.
            message_bus: Message bus for communication.
        """
        self._agent_id: str = agent_id or uuid4().hex[:12]
        self._message_bus: Optional[MessageBus] = message_bus
        self._initialized: bool = False
        self._strategies: Dict[str, Strategy] = {}
        self._signals: List[TradingSignal] = []
        logger.info("StrategyAgent created: %s", self._agent_id)

    # ── Lifecycle ──

    async def initialize(self) -> None:
        """Initialize the strategy agent."""
        if self._initialized:
            return
        self._initialized = True
        logger.info("StrategyAgent initialized: %s", self._agent_id)

    async def shutdown(self) -> None:
        """Shut down the strategy agent."""
        self._strategies.clear()
        self._signals.clear()
        self._initialized = False
        logger.info("StrategyAgent shutdown: %s", self._agent_id)

    # ── Strategy Management ──

    async def develop(
        self, name: str, parameters: Dict[str, Any],
    ) -> Strategy:
        """Create a new strategy.

        Args:
            name: Strategy name.
            parameters: Strategy parameters.

        Returns:
            Created strategy.
        """
        strategy = Strategy(
            name=name,
            description=f"Strategy: {name}",
            parameters=parameters,
        )
        self._strategies[strategy.strategy_id] = strategy

        logger.info("StrategyAgent developed: %s (%s)", name, strategy.strategy_id)
        return strategy

    async def evaluate(self, strategy_id: str) -> Strategy:
        """Evaluate a strategy's performance.

        Args:
            strategy_id: The strategy identifier.

        Returns:
            Updated strategy with metrics.
        """
        strategy = self._strategies.get(strategy_id)
        if not strategy:
            raise KeyError(f"Strategy not found: {strategy_id}")

        strategy.metrics = {
            "sharpe_ratio": 1.5,
            "max_drawdown": -0.15,
            "annual_return": 0.12,
            "calmar_ratio": 0.8,
        }
        strategy.status = StrategyStatus.BACKTESTED

        if self._message_bus:
            await self._message_bus.publish(Message(
                msg_type=MessageType.PUBLISH,
                topic="strategy.evaluated",
                sender_id=self._agent_id,
                payload={"strategy_id": strategy_id, "metrics": strategy.metrics},
            ))

        return strategy

    # ── Signal Generation ──

    async def generate_signals(
        self, strategy_id: str, symbols: Optional[List[str]] = None,
    ) -> List[TradingSignal]:
        """Generate trading signals from a strategy.

        Args:
            strategy_id: The strategy identifier.
            symbols: Optional list of symbols. Uses default if not provided.

        Returns:
            List of trading signals.
        """
        strategy = self._strategies.get(strategy_id)
        if not strategy:
            raise KeyError(f"Strategy not found: {strategy_id}")

        target_symbols = symbols or ["AAPL", "GOOGL"]
        signals: List[TradingSignal] = []

        for symbol in target_symbols:
            signal = TradingSignal(
                strategy_id=strategy_id,
                symbol=symbol,
                direction=SignalDirection.BUY,
                confidence=0.7,
                reason=f"Strategy '{strategy.name}' signal for {symbol}",
            )
            signals.append(signal)
            self._signals.append(signal)

        # Publish signals
        if self._message_bus:
            await self._message_bus.publish(Message(
                msg_type=MessageType.PUBLISH,
                topic="strategy.signals",
                sender_id=self._agent_id,
                payload={
                    "strategy_id": strategy_id,
                    "signal_count": len(signals),
                    "signals": [
                        {"symbol": s.symbol, "direction": s.direction.value, "confidence": s.confidence}
                        for s in signals
                    ],
                },
            ))

        logger.info("StrategyAgent generated %d signals for %s", len(signals), strategy.name)
        return signals

    # ── Lifecycle ──

    async def activate(self, strategy_id: str) -> None:
        """Activate a strategy for live trading.

        Args:
            strategy_id: The strategy identifier.
        """
        strategy = self._strategies.get(strategy_id)
        if strategy:
            strategy.status = StrategyStatus.LIVE
            logger.info("Strategy activated: %s", strategy.name)

    async def pause(self, strategy_id: str) -> None:
        """Pause a strategy.

        Args:
            strategy_id: The strategy identifier.
        """
        strategy = self._strategies.get(strategy_id)
        if strategy:
            strategy.status = StrategyStatus.PAUSED
            logger.info("Strategy paused: %s", strategy.name)

    # ── Properties ──

    @property
    def agent_id(self) -> str:
        """Return the agent ID."""
        return self._agent_id

    # ── Status ──

    def get_summary(self) -> Dict[str, Any]:
        """Return a summary of the strategy agent state.

        Returns:
            Dict with strategy and signal counts.
        """
        return {
            "agent_id": self._agent_id,
            "initialized": self._initialized,
            "total_strategies": len(self._strategies),
            "active_strategies": sum(1 for s in self._strategies.values() if s.status == StrategyStatus.LIVE),
            "total_signals": len(self._signals),
        }
