"""
Auto Hedging Policy — Automated portfolio hedging policies.

Defines rules for when and how to automatically hedge portfolio
risk, including delta hedging, beta hedging, and tail-risk hedging.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

logger = logging.getLogger(__name__)


class HedgeType(str, Enum):
    """Types of hedging strategies."""
    DELTA_NEUTRAL = "DELTA_NEUTRAL"
    BETA_NEUTRAL = "BETA_NEUTRAL"
    TAIL_RISK = "TAIL_RISK"
    CURRENCY = "CURRENCY"
    VOLATILITY = "VOLATILITY"
    CUSTOM = "CUSTOM"


class HedgeTrigger(str, Enum):
    """Triggers for hedge execution."""
    THRESHOLD = "THRESHOLD"
    SCHEDULED = "SCHEDULED"
    EVENT_DRIVEN = "EVENT_DRIVEN"
    MANUAL = "MANUAL"


@dataclass
class HedgingRule:
    """A single hedging rule."""
    rule_id: str
    hedge_type: HedgeType
    trigger: HedgeTrigger = HedgeTrigger.THRESHOLD
    metric: str = "delta"  # What to hedge
    threshold: float = 0.0  # Trigger threshold
    target: float = 0.0  # Target value after hedge
    hedge_ratio: float = 1.0  # How much to hedge (1.0 = full)
    enabled: bool = True
    max_hedge_notional: float = 0.0  # 0 = unlimited
    cooldown_minutes: int = 5
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class HedgeSignal:
    """A hedging signal generated by the policy."""
    signal_id: str
    rule_id: str
    hedge_type: HedgeType
    account_id: str
    metric: str
    current_value: float
    target_value: float
    hedge_amount: float
    direction: str  # "buy" or "sell"
    urgency: str = "NORMAL"  # NORMAL, URGENT, CRITICAL
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "rule_id": self.rule_id,
            "hedge_type": self.hedge_type.value,
            "account_id": self.account_id,
            "metric": self.metric,
            "current_value": self.current_value,
            "target_value": self.target_value,
            "hedge_amount": self.hedge_amount,
            "direction": self.direction,
            "urgency": self.urgency,
        }


class AutoHedgingPolicy:
    """
    Automated portfolio hedging policy engine.

    Evaluates portfolio risk metrics against hedging rules and
    generates hedge signals when thresholds are breached. Supports
    delta-neutral, beta-neutral, tail-risk, and custom hedging.

    Usage::

        policy = AutoHedgingPolicy()
        await policy.initialize()

        policy.add_rule(HedgingRule(
            rule_id="delta_hedge_01",
            hedge_type=HedgeType.DELTA_NEUTRAL,
            metric="delta",
            threshold=100000,
            target=0,
        ))

        signals = await policy.evaluate("ACC-01", portfolio_metrics)
    """

    def __init__(self) -> None:
        self._rules: dict[str, HedgingRule] = {}
        self._signal_history: list[HedgeSignal] = []
        self._last_hedge_time: dict[str, datetime] = {}
        self._lock = asyncio.Lock()
        self._signal_counter: int = 0
        self._initialized = False

    # ---- Lifecycle ----

    async def initialize(self) -> None:
        """Initialize the auto hedging policy."""
        self._initialized = True
        logger.info("AutoHedgingPolicy initialized.")

    async def stop(self) -> None:
        """Stop the auto hedging policy."""
        self._initialized = False
        logger.info("AutoHedgingPolicy stopped.")

    # ---- Rule Management ----

    def add_rule(self, rule: HedgingRule) -> None:
        """Add a hedging rule."""
        self._rules[rule.rule_id] = rule
        logger.info(f"Hedging rule added: {rule.rule_id} ({rule.hedge_type.value})")

    def remove_rule(self, rule_id: str) -> None:
        """Remove a hedging rule."""
        self._rules.pop(rule_id, None)
        logger.info(f"Hedging rule removed: {rule_id}")

    def get_rules(self) -> dict[str, HedgingRule]:
        """Get all hedging rules."""
        return dict(self._rules)

    # ---- Core API ----

    async def evaluate(
        self,
        account_id: str,
        portfolio_metrics: dict[str, float],
    ) -> list[HedgeSignal]:
        """
        Evaluate portfolio metrics against all hedging rules.

        Returns a list of hedge signals for any breached thresholds.
        """
        signals = []

        for rule in self._rules.values():
            if not rule.enabled:
                continue

            # Cooldown check
            last_time = self._last_hedge_time.get(rule.rule_id)
            if last_time:
                elapsed = (datetime.now(timezone.utc) - last_time).total_seconds() / 60
                if elapsed < rule.cooldown_minutes:
                    continue

            metric_value = portfolio_metrics.get(rule.metric)
            if metric_value is None:
                continue

            # Check threshold
            if abs(metric_value) <= abs(rule.threshold):
                continue

            # Compute hedge amount
            hedge_amount = (metric_value - rule.target) * rule.hedge_ratio

            # Cap at max notional
            if rule.max_hedge_notional > 0:
                hedge_amount = min(abs(hedge_amount), rule.max_hedge_notional) * (
                    1 if hedge_amount > 0 else -1
                )

            if abs(hedge_amount) < 1.0:
                continue

            # Determine direction
            direction = "sell" if hedge_amount > 0 else "buy"

            # Urgency
            urgency = "NORMAL"
            if abs(metric_value) > abs(rule.threshold) * 2:
                urgency = "CRITICAL"
            elif abs(metric_value) > abs(rule.threshold) * 1.5:
                urgency = "URGENT"

            self._signal_counter += 1
            signal = HedgeSignal(
                signal_id=f"HEDGE-{self._signal_counter:06d}",
                rule_id=rule.rule_id,
                hedge_type=rule.hedge_type,
                account_id=account_id,
                metric=rule.metric,
                current_value=metric_value,
                target_value=rule.target,
                hedge_amount=hedge_amount,
                direction=direction,
                urgency=urgency,
            )

            signals.append(signal)

            async with self._lock:
                self._signal_history.append(signal)
                self._last_hedge_time[rule.rule_id] = datetime.now(timezone.utc)

        if signals:
            logger.info(f"Generated {len(signals)} hedge signals for {account_id}")

        return signals

    async def evaluate_delta_hedge(
        self,
        account_id: str,
        portfolio_delta: float,
        delta_limit: float = 100000.0,
    ) -> Optional[HedgeSignal]:
        """Quick delta hedge evaluation."""
        metrics = {"delta": portfolio_delta}

        # Ensure rule exists
        rule_id = f"delta_hedge_{account_id}"
        if rule_id not in self._rules:
            self.add_rule(HedgingRule(
                rule_id=rule_id,
                hedge_type=HedgeType.DELTA_NEUTRAL,
                metric="delta",
                threshold=delta_limit,
                target=0.0,
            ))

        signals = await self.evaluate(account_id, metrics)
        return signals[0] if signals else None

    # ---- History ----

    async def get_signal_history(self, limit: int = 100) -> list[HedgeSignal]:
        """Get recent hedge signals."""
        return self._signal_history[-limit:]

    # ---- Stats ----

    async def get_stats(self) -> dict[str, Any]:
        """Get policy statistics."""
        return {
            "rules": {
                rid: {
                    "type": r.hedge_type.value,
                    "enabled": r.enabled,
                    "metric": r.metric,
                    "threshold": r.threshold,
                }
                for rid, r in self._rules.items()
            },
            "total_signals": len(self._signal_history),
        }

    async def health_check(self) -> dict[str, Any]:
        """Check policy health."""
        return {
            "status": "healthy" if self._initialized else "not_initialized",
            "active_rules": sum(1 for r in self._rules.values() if r.enabled),
        }
